"""Canonical V3 command/result/event contracts.

This Python module is the only source of message names.  The checked-in
TypeScript client is generated by ``script/generate_protocol_contracts.py``.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
import re
from typing import Any, ClassVar
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator


PROTOCOL_VERSION = 3
_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
_FINGERPRINT_PATTERN = re.compile(r"^[a-f0-9]{64}$")


LEGACY_MESSAGE_TYPES: tuple[tuple[str, str], ...] = (
    ("CHAT_SEND", "chat:send"),
    ("CHAT_CANCEL", "chat:cancel"),
    ("CHAT_REVEAL", "chat:reveal"),
    ("CHAT_STOP", "chat:stop"),
    ("CHAT_HISTORY", "chat:history"),
    ("BRIDGE_AUTH", "bridge:auth"),
    ("LOCAL_MODE_SET", "local_mode:set"),
    ("MEMORY_QUERY", "memory:query"),
    ("MEMORY_SETTINGS_GET", "memory:settings:get"),
    ("MEMORY_STORE", "memory:store"),
    ("EMOTION_GET", "emotion:get"),
    ("PERSONA_GET", "persona:get"),
    ("PERSONA_IMPORT", "persona:import"),
    ("PERSONA_LIST", "persona:list"),
    ("PERSONA_ACTIVATE", "persona:activate"),
    ("ARCHIVE_GET", "archive:get"),
    ("ARCHIVE_PUT", "archive:put"),
    ("ARCHIVE_MIGRATE", "archive:migrate"),
    ("MODULE_LIST", "module:list"),
    ("MODULE_CONTROL", "module:control"),
    ("GAME_STATE_GET", "game_state:get"),
    ("GAME_STATE_PUT", "game_state:put"),
    ("RELATIONSHIP_GET", "relationship:get"),
    ("DIARY_REQUEST", "diary:request"),
    ("TIMELINE_REQUEST", "timeline:request"),
    ("AMBIENT_GET", "ambient:get"),
    ("API_BUDGET_GET", "api:budget:get"),
    ("GROUP_REQUEST", "group:request"),
    ("GROUP_SEND", "group:send"),
    ("IMAGE_RANDOM", "image:random"),
    ("SETTINGS_UPDATE", "settings:update"),
    ("SETTINGS_GET", "settings:get"),
    ("AI_USAGE_GET", "ai_usage:get"),
    ("AI_USAGE_GRANT", "ai_usage:grant"),
    ("AI_USAGE_REVOKE", "ai_usage:revoke"),
    ("USER_PROFILE_GET", "user:profile:get"),
    ("USER_PROFILE_UPDATE", "user:profile:update"),
    ("KEEPSAKE_LIST", "keepsake:list"),
    ("KEEPSAKE_ADD", "keepsake:add"),
    ("BACKUP_EXPORT", "backup:export"),
    ("BACKUP_IMPORT", "backup:import"),
    ("STICKER_LIST", "sticker:list"),
    ("STICKER_COLLECT", "sticker:collect"),
    ("STICKER_REACT", "sticker:react"),
    ("STICKER_SEND", "sticker:send"),
    ("ANTI_AI_STATUS", "anti_ai:status"),
    ("IMMERSION_NEARBY", "immersion:nearby"),
    ("IMMERSION_CLOSEUP", "immersion:closeup"),
    ("IMMERSION_SMART_HOME", "immersion:smart_home"),
    ("CHAT_CHUNK", "chat:chunk"),
    ("CHAT_BUBBLE", "chat:bubble"),
    ("CHAT_DONE", "chat:done"),
    ("CHAT_TYPING", "chat:typing"),
    ("CHAT_STATE", "chat:state"),
    ("CHAT_ERROR", "chat:error"),
    ("CHAT_RETRACT", "chat:retract"),
    ("CHAT_HISTORY_RESULT", "chat:history:result"),
    ("BRIDGE_AUTH_OK", "bridge:auth_ok"),
    ("BRIDGE_AUTH_ERROR", "bridge:auth_error"),
    ("LOCAL_MODE_STATE", "local_mode:state"),
    ("PROACTIVE_MESSAGE", "proactive:message"),
    ("PROACTIVE_NOTIFY", "proactive:notify"),
    ("EMOTION_UPDATE", "emotion:update"),
    ("MEMORY_RESULT", "memory:result"),
    ("MEMORY_SETTINGS_RESULT", "memory:settings:result"),
    ("PERSONA_DATA", "persona:data"),
    ("PERSONA_IMPORT_RESULT", "persona:import:result"),
    ("ARCHIVE_RESULT", "archive:result"),
    ("MODULE_RESULT", "module:result"),
    ("GAME_STATE_RESULT", "game_state:result"),
    ("RELATIONSHIP_DATA", "relationship:data"),
    ("DIARY_RESULT", "diary:result"),
    ("TIMELINE_RESULT", "timeline:result"),
    ("AMBIENT_RESULT", "ambient:result"),
    ("API_BUDGET_RESULT", "api:budget:result"),
    ("GROUP_RESULT", "group:result"),
    ("IMAGE_RESULT", "image:result"),
    ("USER_PROFILE_RESULT", "user:profile:result"),
    ("KEEPSAKE_RESULT", "keepsake:result"),
    ("BACKUP_RESULT", "backup:result"),
    ("SETTINGS_UPDATE_RESULT", "settings:update:result"),
    ("SETTINGS_GET_RESULT", "settings:get:result"),
    ("AI_USAGE_RESULT", "ai_usage:result"),
    ("RUNTIME_ACTIVITY", "runtime:activity"),
    ("STICKER_DATA", "sticker:data"),
    ("ANTI_AI_STATUS_RESULT", "anti_ai:status:result"),
    ("IMMERSION_RESULT", "immersion:result"),
    ("ERROR", "error"),
    ("HEARTBEAT", "heartbeat"),
)

COMMAND_NAMES = frozenset(
    value
    for name, value in LEGACY_MESSAGE_TYPES
    if name
    in {
        "CHAT_SEND",
        "CHAT_CANCEL",
        "CHAT_REVEAL",
        "CHAT_STOP",
        "CHAT_HISTORY",
        "LOCAL_MODE_SET",
        "MEMORY_QUERY",
        "MEMORY_SETTINGS_GET",
        "MEMORY_STORE",
        "EMOTION_GET",
        "PERSONA_GET",
        "PERSONA_IMPORT",
        "PERSONA_LIST",
        "PERSONA_ACTIVATE",
        "ARCHIVE_GET",
        "ARCHIVE_PUT",
        "ARCHIVE_MIGRATE",
        "MODULE_LIST",
        "MODULE_CONTROL",
        "GAME_STATE_GET",
        "GAME_STATE_PUT",
        "RELATIONSHIP_GET",
        "DIARY_REQUEST",
        "TIMELINE_REQUEST",
        "AMBIENT_GET",
        "API_BUDGET_GET",
        "GROUP_REQUEST",
        "GROUP_SEND",
        "IMAGE_RANDOM",
        "SETTINGS_UPDATE",
        "SETTINGS_GET",
        "AI_USAGE_GET",
        "AI_USAGE_GRANT",
        "AI_USAGE_REVOKE",
        "USER_PROFILE_GET",
        "USER_PROFILE_UPDATE",
        "KEEPSAKE_LIST",
        "KEEPSAKE_ADD",
        "BACKUP_EXPORT",
        "BACKUP_IMPORT",
        "STICKER_LIST",
        "STICKER_COLLECT",
        "STICKER_REACT",
        "STICKER_SEND",
        "ANTI_AI_STATUS",
        "IMMERSION_NEARBY",
        "IMMERSION_CLOSEUP",
        "IMMERSION_SMART_HOME",
    }
)


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    STALE_PERSONA = "STALE_PERSONA"
    MODULE_UNAVAILABLE = "MODULE_UNAVAILABLE"
    MODULE_DEGRADED = "MODULE_DEGRADED"
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    LOCAL_MODE_BLOCKED = "LOCAL_MODE_BLOCKED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_OUTCOME_UNKNOWN = "PROVIDER_OUTCOME_UNKNOWN"
    CONFLICT = "CONFLICT"
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    INTERNAL = "INTERNAL"


class _ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class PersonaScopeV3(_ContractModel):
    persona_id: str = Field(min_length=1, max_length=128)
    epoch: int = Field(ge=1)
    fingerprint: str = Field(pattern=_FINGERPRINT_PATTERN.pattern)

    @field_validator("persona_id")
    @classmethod
    def validate_persona_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("persona_id contains unsupported characters")
        return value


class CommandEnvelopeV3(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    request_id: str = Field(default_factory=lambda: uuid4().hex)
    idempotency_key: str = Field(default_factory=lambda: uuid4().hex)
    command: str = Field(min_length=1, max_length=128)
    persona: PersonaScopeV3
    payload: dict[str, Any] = Field(default_factory=dict)
    causation_id: str | None = Field(default=None, max_length=128)
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, value: int) -> int:
        if value != PROTOCOL_VERSION:
            raise ValueError(f"unsupported protocol version: {value}")
        return value

    @field_validator("request_id", "idempotency_key")
    @classmethod
    def validate_identifier(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("identifier contains unsupported characters")
        return value

    @field_validator("command")
    @classmethod
    def validate_command(cls, value: str) -> str:
        if value not in COMMAND_NAMES:
            raise ValueError(f"unknown command: {value}")
        return value


class DomainError(_ContractModel):
    code: ErrorCode
    message: str = Field(min_length=1, max_length=500)
    retryable: bool = False
    details: dict[str, Any] = Field(default_factory=dict)


class CommandResultV3(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    request_id: str
    ok: bool
    data: dict[str, Any] | list[Any] | str | int | float | bool | None = None
    error: DomainError | None = None

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, value: int) -> int:
        if value != PROTOCOL_VERSION:
            raise ValueError(f"unsupported protocol version: {value}")
        return value

    @classmethod
    def success(cls, request_id: str, data: Any = None) -> "CommandResultV3":
        return cls(request_id=request_id, ok=True, data=data)

    @classmethod
    def failure(
        cls,
        request_id: str,
        *,
        code: ErrorCode,
        message: str,
        retryable: bool = False,
        details: dict[str, Any] | None = None,
    ) -> "CommandResultV3":
        return cls(
            request_id=request_id,
            ok=False,
            error=DomainError(
                code=code,
                message=message,
                retryable=retryable,
                details=details or {},
            ),
        )

    def model_post_init(self, __context: Any) -> None:
        if self.ok and self.error is not None:
            raise ValueError("successful result cannot carry an error")
        if not self.ok and self.error is None:
            raise ValueError("failed result must carry an error")


class DomainEventV3(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    event_id: str = Field(default_factory=lambda: uuid4().hex)
    event_type: str = Field(min_length=1, max_length=128)
    persona: PersonaScopeV3
    payload: dict[str, Any] = Field(default_factory=dict)
    causation_id: str | None = Field(default=None, max_length=128)
    occurred_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    payload_version: int = Field(default=1, ge=1)

    @field_validator("event_id", "event_type")
    @classmethod
    def validate_identifier(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("event identifier contains unsupported characters")
        return value


class V2FrameAdapter:
    """Temporary compatibility boundary for the renderer's legacy frames."""

    legacy_protocol_version: ClassVar[int] = 2

    @staticmethod
    def to_v3(frame: dict[str, Any], persona: PersonaScopeV3) -> CommandEnvelopeV3:
        if not isinstance(frame, dict):
            raise TypeError("legacy frame must be an object")
        command = frame.get("type")
        payload = frame.get("payload", {})
        if not isinstance(command, str) or command not in COMMAND_NAMES:
            raise ValueError("legacy frame has an unknown command")
        if not isinstance(payload, dict):
            raise TypeError("legacy frame payload must be an object")
        request_id = str(frame.get("request_id") or uuid4().hex)
        idempotency_key = str(
            payload.get("idempotency_key")
            or payload.get("client_request_id")
            or request_id
        )
        return CommandEnvelopeV3(
            request_id=request_id,
            idempotency_key=idempotency_key,
            command=command,
            persona=persona,
            payload=payload,
        )

    @staticmethod
    def result_to_v2(
        result: CommandResultV3,
        *,
        response_type: str,
    ) -> dict[str, Any]:
        if result.ok:
            payload = result.data
        else:
            assert result.error is not None
            payload = {
                "ok": False,
                "error": {
                    "code": result.error.code.value,
                    "message": result.error.message,
                    "retryable": result.error.retryable,
                },
            }
        return {
            "type": response_type,
            "request_id": result.request_id,
            "payload": payload,
        }


def public_error_message(error: BaseException) -> str:
    """Return a bounded message that cannot impersonate the companion."""

    code = str(getattr(error, "code", "") or "")
    known = {
        "REVERIE_SECURE_STORAGE_UNAVAILABLE": "系统安全凭据存储当前不可用。",
        "REVERIE_VAULT_CORRUPT": "本地凭据保险库无法解密，请先清理或恢复。",
        "REVERIE_VAULT_IO": "本地凭据保险库无法读写。",
    }
    return known.get(code, "请求未完成。技术详情已写入本地日志。")
