"""Canonical V4 command/result/event contracts.

This Python module is the only source of message names.  The checked-in
TypeScript client is generated by ``script/generate_protocol_contracts.py``.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
import re
from typing import Any, ClassVar, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, field_validator, model_validator


PROTOCOL_VERSION = 4
_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
_FINGERPRINT_PATTERN = re.compile(r"^[a-f0-9]{64}$")
_CANDIDATE_ID_PATTERN = re.compile(r"^mc_[a-f0-9]{32}$")


LEGACY_MESSAGE_TYPES: tuple[tuple[str, str], ...] = (
    ("CHAT_SEND", "chat:send"),
    ("CHAT_CANCEL", "chat:cancel"),
    ("CHAT_REVEAL", "chat:reveal"),
    ("CHAT_STOP", "chat:stop"),
    ("CHAT_HISTORY", "chat:history"),
    ("BRIDGE_AUTH", "bridge:auth"),
    ("LOCAL_MODE_SET", "local_mode:set"),
    ("MEMORY_QUERY", "memory:query"),
    ("MEMORY_LIST", "memory:list"),
    ("MEMORY_EDIT", "memory:edit"),
    ("MEMORY_DELETE", "memory:delete"),
    ("MEMORY_SETTINGS_GET", "memory:settings:get"),
    ("MEMORY_STORE", "memory:store"),
    ("MEMORY_CANDIDATE_LIST", "memory:candidates:list"),
    ("MEMORY_CANDIDATE_CONFIRM", "memory:candidates:confirm"),
    ("MEMORY_CANDIDATE_REJECT", "memory:candidates:reject"),
    ("EMOTION_GET", "emotion:get"),
    ("PERSONA_GET", "persona:get"),
    ("PERSONA_IMPORT", "persona:import"),
    ("PERSONA_LIST", "persona:list"),
    ("PERSONA_ACTIVATE", "persona:activate"),
    ("ARCHIVE_GET", "archive:get"),
    ("ARCHIVE_PUT", "archive:put"),
    ("ARCHIVE_MIGRATE", "archive:migrate"),
    ("MODULE_LIST", "module:list"),
    ("MODULE_CONTROL", "module:control"),
    ("GAME_STATE_GET", "game_state:get"),
    ("GAME_STATE_PUT", "game_state:put"),
    ("RELATIONSHIP_GET", "relationship:get"),
    ("DIARY_REQUEST", "diary:request"),
    ("TIMELINE_REQUEST", "timeline:request"),
    ("AMBIENT_GET", "ambient:get"),
    ("API_BUDGET_GET", "api:budget:get"),
    ("GROUP_REQUEST", "group:request"),
    ("GROUP_SEND", "group:send"),
    ("IMAGE_RANDOM", "image:random"),
    ("SETTINGS_UPDATE", "settings:update"),
    ("SETTINGS_GET", "settings:get"),
    ("AI_USAGE_GET", "ai_usage:get"),
    ("AI_USAGE_GRANT", "ai_usage:grant"),
    ("AI_USAGE_REVOKE", "ai_usage:revoke"),
    ("USER_PROFILE_GET", "user:profile:get"),
    ("USER_PROFILE_UPDATE", "user:profile:update"),
    ("KEEPSAKE_LIST", "keepsake:list"),
    ("KEEPSAKE_ADD", "keepsake:add"),
    ("BACKUP_EXPORT", "backup:export"),
    ("BACKUP_IMPORT", "backup:import"),
    ("STICKER_LIST", "sticker:list"),
    ("STICKER_COLLECT", "sticker:collect"),
    ("STICKER_REACT", "sticker:react"),
    ("STICKER_SEND", "sticker:send"),
    ("ANTI_AI_STATUS", "anti_ai:status"),
    ("IMMERSION_NEARBY", "immersion:nearby"),
    ("IMMERSION_CLOSEUP", "immersion:closeup"),
    ("IMMERSION_SMART_HOME", "immersion:smart_home"),
    ("CHAT_CHUNK", "chat:chunk"),
    ("CHAT_BUBBLE", "chat:bubble"),
    ("CHAT_DONE", "chat:done"),
    ("CHAT_TYPING", "chat:typing"),
    ("CHAT_STATE", "chat:state"),
    ("CHAT_ERROR", "chat:error"),
    ("CHAT_RETRACT", "chat:retract"),
    ("CHAT_HISTORY_RESULT", "chat:history:result"),
    ("BRIDGE_AUTH_OK", "bridge:auth_ok"),
    ("BRIDGE_AUTH_ERROR", "bridge:auth_error"),
    ("LOCAL_MODE_STATE", "local_mode:state"),
    ("PROACTIVE_MESSAGE", "proactive:message"),
    ("PROACTIVE_NOTIFY", "proactive:notify"),
    ("EMOTION_UPDATE", "emotion:update"),
    ("MEMORY_RESULT", "memory:result"),
    ("MEMORY_SETTINGS_RESULT", "memory:settings:result"),
    ("MEMORY_CANDIDATE_RESULT", "memory:candidates:result"),
    ("PERSONA_DATA", "persona:data"),
    ("PERSONA_IMPORT_RESULT", "persona:import:result"),
    ("ARCHIVE_RESULT", "archive:result"),
    ("MODULE_RESULT", "module:result"),
    ("GAME_STATE_RESULT", "game_state:result"),
    ("RELATIONSHIP_DATA", "relationship:data"),
    ("DIARY_RESULT", "diary:result"),
    ("TIMELINE_RESULT", "timeline:result"),
    ("AMBIENT_RESULT", "ambient:result"),
    ("API_BUDGET_RESULT", "api:budget:result"),
    ("GROUP_RESULT", "group:result"),
    ("IMAGE_RESULT", "image:result"),
    ("USER_PROFILE_RESULT", "user:profile:result"),
    ("KEEPSAKE_RESULT", "keepsake:result"),
    ("BACKUP_RESULT", "backup:result"),
    ("SETTINGS_UPDATE_RESULT", "settings:update:result"),
    ("SETTINGS_GET_RESULT", "settings:get:result"),
    ("AI_USAGE_RESULT", "ai_usage:result"),
    ("RUNTIME_ACTIVITY", "runtime:activity"),
    ("STICKER_DATA", "sticker:data"),
    ("ANTI_AI_STATUS_RESULT", "anti_ai:status:result"),
    ("IMMERSION_RESULT", "immersion:result"),
    ("ERROR", "error"),
    ("HEARTBEAT", "heartbeat"),
)

MVP_COMMAND_NAMES = frozenset(
    value
    for name, value in LEGACY_MESSAGE_TYPES
    if name
    in {
        "CHAT_SEND",
        "CHAT_CANCEL",
        "CHAT_STOP",
        "CHAT_REVEAL",
        "CHAT_HISTORY",
        "MEMORY_QUERY",
        "MEMORY_LIST",
        "MEMORY_STORE",
        "MEMORY_EDIT",
        "MEMORY_DELETE",
        "MEMORY_SETTINGS_GET",
        "MEMORY_CANDIDATE_LIST",
        "MEMORY_CANDIDATE_CONFIRM",
        "MEMORY_CANDIDATE_REJECT",
        "GROUP_REQUEST",
        "GROUP_SEND",
        "STICKER_LIST",
        "STICKER_COLLECT",
        "STICKER_REACT",
        "GAME_STATE_GET",
        "GAME_STATE_PUT",
        "IMMERSION_NEARBY",
        "IMMERSION_CLOSEUP",
        "IMMERSION_SMART_HOME",
        "AMBIENT_GET",
        "API_BUDGET_GET",
        "ARCHIVE_GET",
        "ARCHIVE_PUT",
        "ARCHIVE_MIGRATE",
        "MODULE_LIST",
        "MODULE_CONTROL",
        "DIARY_REQUEST",
        "TIMELINE_REQUEST",
        "KEEPSAKE_LIST",
        "KEEPSAKE_ADD",
        "BACKUP_EXPORT",
        "BACKUP_IMPORT",
        "IMAGE_RANDOM",
        "EMOTION_GET",
        "PERSONA_GET",
        "PERSONA_IMPORT",
        "PERSONA_ACTIVATE",
        "RELATIONSHIP_GET",
        "SETTINGS_UPDATE",
        "SETTINGS_GET",
        "AI_USAGE_GET",
        "AI_USAGE_GRANT",
        "AI_USAGE_REVOKE",
        "USER_PROFILE_GET",
        "USER_PROFILE_UPDATE",
        "ANTI_AI_STATUS",
    }
)
MVP_EVENT_NAMES = frozenset(
    value
    for name, value in LEGACY_MESSAGE_TYPES
    if name
    in {
        "CHAT_CHUNK",
        "CHAT_BUBBLE",
        "CHAT_DONE",
        "CHAT_TYPING",
        "CHAT_STATE",
        "CHAT_ERROR",
        "CHAT_RETRACT",
        "CHAT_HISTORY_RESULT",
        "EMOTION_UPDATE",
        "MEMORY_RESULT",
        "MEMORY_SETTINGS_RESULT",
        "MEMORY_CANDIDATE_RESULT",
        "GROUP_RESULT",
        "STICKER_DATA",
        "GAME_STATE_RESULT",
        "IMMERSION_RESULT",
        "AMBIENT_RESULT",
        "API_BUDGET_RESULT",
        "ARCHIVE_RESULT",
        "MODULE_RESULT",
        "DIARY_RESULT",
        "TIMELINE_RESULT",
        "KEEPSAKE_RESULT",
        "BACKUP_RESULT",
        "IMAGE_RESULT",
        "PROACTIVE_MESSAGE",
        "RUNTIME_ACTIVITY",
        "PERSONA_DATA",
        "PERSONA_IMPORT_RESULT",
        "AI_USAGE_RESULT",
        "RELATIONSHIP_DATA",
        "USER_PROFILE_RESULT",
        "SETTINGS_UPDATE_RESULT",
        "SETTINGS_GET_RESULT",
        "ANTI_AI_STATUS_RESULT",
        "ERROR",
        "HEARTBEAT",
    }
)
# Compatibility import name for callers which only need the production
# allowlist. V4 intentionally does not expose retired feature commands.
COMMAND_NAMES = MVP_COMMAND_NAMES


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    STALE_PERSONA = "STALE_PERSONA"
    MODULE_UNAVAILABLE = "MODULE_UNAVAILABLE"
    MODULE_DEGRADED = "MODULE_DEGRADED"
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    LOCAL_MODE_BLOCKED = "LOCAL_MODE_BLOCKED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_OUTCOME_UNKNOWN = "PROVIDER_OUTCOME_UNKNOWN"
    CONFLICT = "CONFLICT"
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    INTERNAL = "INTERNAL"


class _ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class _PayloadModel(BaseModel):
    """Strict command payload parsed again at the trusted Python boundary."""

    model_config = ConfigDict(extra="forbid", frozen=True)


class EmptyPayload(_PayloadModel):
    pass


class ChatSendPayload(_PayloadModel):
    text: str = Field(min_length=1, max_length=20_000)
    request_id: str | None = Field(default=None, max_length=128)
    conversation_id: str = Field(default="dream-room", min_length=1, max_length=160)
    sent_at_utc: str | None = Field(default=None, max_length=64)

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str | None) -> str | None:
        if value is not None and not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value

    @field_validator("conversation_id")
    @classmethod
    def validate_conversation_id(cls, value: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9._:-]{1,160}", value):
            raise ValueError("conversation_id contains unsupported characters")
        return value


class ChatTargetPayload(_PayloadModel):
    request_id: str = Field(min_length=1, max_length=128)

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value


class ChatStopPayload(_PayloadModel):
    """Legacy stop alias.

    ``request_id`` is optional because ``handle_chat_stop`` answers with a
    dedicated ERROR frame instead of a generic validation failure when the
    controller does not name a specific request (global cancellation is
    forbidden by design).
    """

    request_id: str | None = Field(default=None, max_length=128)

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str | None) -> str | None:
        if value is not None and not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value


class AIUsageGrantPayload(_PayloadModel):
    """Per-feature consent grant. Booleans must be exactly ``True`` to mirror
    the bridge handler's ``is not True`` checks (no truthy coercion)."""

    model_config = ConfigDict(strict=True, extra="forbid", frozen=True)

    feature: str = Field(min_length=1, max_length=80)
    consent_digest: str = Field(min_length=1, max_length=128)
    api_cost_acknowledged: StrictBool
    user_confirmed: StrictBool

    @field_validator("api_cost_acknowledged", "user_confirmed")
    @classmethod
    def must_be_true(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("explicit confirmation must be exactly true")
        return value


class AIUsageRevokePayload(_PayloadModel):
    feature: str = Field(min_length=1, max_length=80)


class PersonaImportPayload(_PayloadModel):
    """Untrusted SillyTavern JSON card; the importer re-validates size/depth.

    The wire field is ``json``; the attribute is ``json_text`` (serialized
    back as ``json`` via the alias) to avoid shadowing pydantic's historical
    ``json`` helper attribute.
    """

    model_config = ConfigDict(serialize_by_alias=True, extra="forbid", frozen=True)

    json_text: str = Field(
        alias="json",
        validation_alias="json",
        min_length=1,
        max_length=2_000_000,
    )
    filename: str = Field(default="character.json", min_length=1, max_length=256)


class PersonaActivatePayload(_PayloadModel):
    """Explicit identity switch. ``expected_persona_*`` is injected by the
    bridge from the active scope, not part of the client contract."""

    model_config = ConfigDict(strict=True, extra="forbid", frozen=True)

    profile_id: str = Field(min_length=1, max_length=160)
    identity_change_confirmed: StrictBool
    confirmed_profile_id: str = Field(min_length=1, max_length=160)
    actor: Literal["owner", "local_admin"]
    reason: str = Field(min_length=3, max_length=500)

    @field_validator("identity_change_confirmed")
    @classmethod
    def must_be_true(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("identity change confirmation must be exactly true")
        return value


class KeepsakeAddPayload(_PayloadModel):
    kind: str = Field(default="text", min_length=1, max_length=40)
    title: str = Field(default="", max_length=80)
    content: str = Field(default="", max_length=1200)
    source_path: str = Field(default="", max_length=1000)
    media_data_url: str = Field(default="", max_length=2_097_152)
    tags: list[str] = Field(default_factory=list, max_length=50)
    importance: float = Field(default=0.5, ge=0.0, le=1.0)


class ArchivePutPayload(_PayloadModel):
    """Archive write; deep validation happens in the archive store."""

    archive: dict[str, Any] = Field(default_factory=dict)
    expected_revision: StrictInt = Field(default=0, ge=0)


class ModuleControlPayload(_PayloadModel):
    module_id: str = Field(min_length=1, max_length=64, pattern=r"^[a-z][a-z0-9._-]{0,63}$")
    action: str = Field(min_length=1, max_length=32)


class ChatHistoryCursor(_PayloadModel):
    sequence: int = Field(ge=1)


class ChatHistoryPayload(_PayloadModel):
    conversation_id: str = Field(default="dream-room", min_length=1, max_length=160)
    limit: int = Field(default=300, ge=1, le=300)
    before: ChatHistoryCursor | None = None

    @field_validator("conversation_id")
    @classmethod
    def validate_conversation_id(cls, value: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9._:-]{1,160}", value):
            raise ValueError("conversation_id contains unsupported characters")
        return value


class MemoryQueryPayload(_PayloadModel):
    query: str = Field(min_length=1, max_length=2_000)
    top_k: int = Field(default=10, ge=1, le=50)


class MemoryListPayload(_PayloadModel):
    limit: int = Field(default=100, ge=1, le=200)


class MemoryTargetPayload(_PayloadModel):
    memory_id: str = Field(min_length=1, max_length=128)

    @field_validator("memory_id")
    @classmethod
    def validate_memory_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("memory_id contains unsupported characters")
        return value


class MemoryStorePayload(_PayloadModel):
    """Store a user-selected chat record in a memory layer.

    ``permanent`` marks a precious memory (never decays, never confused);
    ``long_term``/``short_term`` remain forgettable.
    """

    text: str = Field(min_length=1, max_length=2_000)
    layer: Literal["long_term", "short_term", "permanent"] = "long_term"

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("memory text cannot be blank")
        return cleaned


class MemoryEditPayload(MemoryTargetPayload):
    text: str = Field(min_length=1, max_length=2_000)

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("memory correction cannot be blank")
        return cleaned


class MemoryCandidateListPayload(_PayloadModel):
    status: Literal["pending", "confirmed", "rejected", "all"] = "pending"
    limit: int = Field(default=100, ge=1, le=200)


class MemoryCandidateDecisionPayload(_PayloadModel):
    candidate_id: str = Field(pattern=_CANDIDATE_ID_PATTERN.pattern)


class GroupSendPayload(_PayloadModel):
    """Send one message into the local role-world group chat."""

    text: str = Field(min_length=1, max_length=2_000)
    thread_id: str = Field(default="local-friends", min_length=1, max_length=120)
    user_name: str = Field(default="你", min_length=1, max_length=40)

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("group message cannot be blank")
        return cleaned


class StickerListPayload(_PayloadModel):
    """List user-collected and default stickers."""

    limit: int = Field(default=100, ge=1, le=200)


class StickerCollectPayload(_PayloadModel):
    """Collect a user-provided sticker image or text with emotion/style tags."""

    text: str = Field(default="", max_length=400)
    emotions: list[str] = Field(default_factory=list, max_length=24)
    style_tags: list[str] = Field(default_factory=list, max_length=24)
    image_data_url: str = Field(default="", max_length=16_000_000)


class StickerReactPayload(_PayloadModel):
    """Record user feedback for sticker reuse preferences."""

    id: str = Field(min_length=1, max_length=128)
    liked: bool = True


class GameStateGetPayload(_PayloadModel):
    """Read persisted state for one local mini-game."""

    game_id: str = Field(min_length=1, max_length=64, pattern=r"^[a-z][a-z0-9._-]{0,63}$")


class GameStatePutPayload(GameStateGetPayload):
    """Persist bounded state for one local mini-game."""

    state: dict[str, Any] = Field(default_factory=dict)
    expected_revision: int = Field(default=0, ge=0, le=1_000_000)


class ImmersionNearbyPayload(_PayloadModel):
    """Request nearby life context from a user-granted coarse location."""

    latitude: float = Field(ge=-90.0, le=90.0)
    longitude: float = Field(ge=-180.0, le=180.0)
    place_types: list[str] = Field(default_factory=list, max_length=6)
    radius_m: int = Field(default=1200, ge=300, le=5000)

    @field_validator("place_types")
    @classmethod
    def validate_place_types(cls, value: list[str]) -> list[str]:
        allowed = {"restaurant", "shop", "cafe", "supermarket", "park", "mall"}
        seen: list[str] = []
        for item in value:
            kind = str(item).strip().lower()
            if kind in allowed and kind not in seen:
                seen.append(kind)
        return seen


class ImmersionCloseupPayload(_PayloadModel):
    """Request a multimodal close-up generation plan."""

    kind: Literal["meal", "cooking", "bath", "shopping"] = "meal"


class ImmersionSmartHomePayload(_PayloadModel):
    """Issue a safe dry-run smart-home command envelope."""

    provider: Literal["manual", "xiaomi", "huawei"] = "manual"
    device: str = Field(min_length=1, max_length=40)
    action: str = Field(min_length=1, max_length=80)


class DiaryRequestPayload(_PayloadModel):
    """Request diary data; optional unlock_key action for the easter egg."""

    action: Literal["list", "read", "unlock_key"] = "list"
    date: str = Field(default="", max_length=32)
    host_date: str = Field(default="", max_length=32)


class KeepsakeListPayload(_PayloadModel):
    """List collected keepsakes."""

    limit: int = Field(default=20, ge=1, le=200)


class BackupImportPayload(_PayloadModel):
    """Restore the complete local memory state from a JSON-safe payload."""

    backup: dict[str, Any] = Field(default_factory=dict)


class ImageRandomPayload(_PayloadModel):
    """Request a random image from the optional local image service."""

    mode: Literal["sfw", "nsfw", "random"] = "sfw"


class SettingsUpdatePayload(_PayloadModel):
    """The small settings surface that exists in the current MVP."""

    section: Literal["onboarding", "memory", "chat", "personality", "features", "ui"]
    completed: bool | None = None
    mode: Literal["mvp", "dream"] | None = None

    retention_days: Literal[365, 730, 1095] | None = None
    forgetting_enabled: bool | None = None
    long_term_forgetting_enabled: bool | None = None
    short_term_forgetting_enabled: bool | None = None
    long_term_forget_days: int | None = Field(default=None, ge=60, le=365)
    short_term_forget_days: int | None = Field(default=None, ge=1, le=59)
    long_term_forget_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    short_term_forget_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    decay_lambda: float | None = Field(default=None, ge=0.0001, le=0.10)
    recall_reinforcement_alpha: float | None = Field(default=None, ge=0.0, le=0.50)
    minimum_retrieval_retention: float | None = Field(default=None, ge=0.0, le=0.95)

    reply_delay_min: float | None = Field(default=None, ge=1.0, le=60.0)
    reply_delay_max: float | None = Field(default=None, ge=1.0, le=60.0)
    split_messages: bool | None = None
    typing_indicator: bool | None = None
    allow_environment_description: bool | None = None
    status: Literal["online", "busy", "away", "sleeping"] | None = None

    personality_flaws_enabled: bool | None = None
    personality_flaws_disclaimer_acknowledged: bool | None = None
    user_selected_flaws: str | None = Field(default=None, max_length=400)

    proactive_chat_enabled: bool | None = None
    proactive_notifications_enabled: bool | None = None
    proactive_daily_limit: int | None = Field(default=None, ge=1, le=12)
    proactive_min_interval_minutes: int | None = Field(default=None, ge=15, le=1440)

    @model_validator(mode="after")
    def validate_section_fields(self) -> "SettingsUpdatePayload":
        allowed = {
            "onboarding": {"section", "completed"},
            "memory": {
                "section",
                "retention_days",
                "forgetting_enabled",
                "long_term_forgetting_enabled",
                "short_term_forgetting_enabled",
                "long_term_forget_days",
                "short_term_forget_days",
                "long_term_forget_probability",
                "short_term_forget_probability",
                "decay_lambda",
                "recall_reinforcement_alpha",
                "minimum_retrieval_retention",
            },
            "chat": {
                "section",
                "reply_delay_min",
                "reply_delay_max",
                "split_messages",
                "typing_indicator",
                "allow_environment_description",
                "status",
            },
            "personality": {
                "section",
                "personality_flaws_enabled",
                "personality_flaws_disclaimer_acknowledged",
                "user_selected_flaws",
            },
            "features": {
                "section",
                "proactive_chat_enabled",
                "proactive_notifications_enabled",
                "proactive_daily_limit",
                "proactive_min_interval_minutes",
            },
            "ui": {
                "section",
                "mode",
            },
        }[self.section]
        unexpected = self.model_fields_set - allowed
        if unexpected:
            raise ValueError(
                f"settings section {self.section} does not accept: "
                + ", ".join(sorted(unexpected))
            )
        if self.section == "onboarding" and self.completed is None:
            raise ValueError("onboarding settings require completed")
        return self


class UserProfileData(_PayloadModel):
    name: str = Field(default="", max_length=80)
    nickname: str = Field(default="", max_length=80)
    age: int | None = Field(default=None, ge=18, le=120)
    birthday: str = Field(default="", max_length=10)
    identity: str = Field(default="", max_length=500)
    schedule: str = Field(default="", max_length=200)
    interests: list[str] = Field(default_factory=list, max_length=50)
    hobbies: list[str] = Field(default_factory=list, max_length=50)
    favorite_topics: list[str] = Field(default_factory=list, max_length=50)
    favorite_games: list[str] = Field(default_factory=list, max_length=50)
    favorite_anime: list[str] = Field(default_factory=list, max_length=50)
    important_dates: dict[str, str] = Field(default_factory=dict, max_length=50)

    @model_validator(mode="after")
    def validate_bounded_collections(self) -> "UserProfileData":
        for field_name in (
            "interests",
            "hobbies",
            "favorite_topics",
            "favorite_games",
            "favorite_anime",
        ):
            if any(not item.strip() or len(item) > 160 for item in getattr(self, field_name)):
                raise ValueError(f"{field_name} contains an invalid item")
        if any(
            not key.strip()
            or len(key) > 80
            or not value.strip()
            or len(value) > 32
            for key, value in self.important_dates.items()
        ):
            raise ValueError("important_dates contains an invalid entry")
        return self


class UserProfileUpdatePayload(_PayloadModel):
    profile: UserProfileData


COMMAND_PAYLOAD_MODELS: dict[str, type[_PayloadModel]] = {
    "chat:send": ChatSendPayload,
    "chat:cancel": ChatTargetPayload,
    "chat:stop": ChatStopPayload,
    "chat:reveal": ChatTargetPayload,
    "chat:history": ChatHistoryPayload,
    "memory:query": MemoryQueryPayload,
    "memory:list": MemoryListPayload,
    "memory:store": MemoryStorePayload,
    "memory:edit": MemoryEditPayload,
    "memory:delete": MemoryTargetPayload,
    "memory:settings:get": EmptyPayload,
    "memory:candidates:list": MemoryCandidateListPayload,
    "memory:candidates:confirm": MemoryCandidateDecisionPayload,
    "memory:candidates:reject": MemoryCandidateDecisionPayload,
    "group:request": EmptyPayload,
    "group:send": GroupSendPayload,
    "sticker:list": StickerListPayload,
    "sticker:collect": StickerCollectPayload,
    "sticker:react": StickerReactPayload,
    "game_state:get": GameStateGetPayload,
    "game_state:put": GameStatePutPayload,
    "immersion:nearby": ImmersionNearbyPayload,
    "immersion:closeup": ImmersionCloseupPayload,
    "immersion:smart_home": ImmersionSmartHomePayload,
    "ambient:get": EmptyPayload,
    "api:budget:get": EmptyPayload,
    "archive:get": EmptyPayload,
    "archive:put": ArchivePutPayload,
    "archive:migrate": ArchivePutPayload,
    "module:list": EmptyPayload,
    "module:control": ModuleControlPayload,
    "diary:request": DiaryRequestPayload,
    "timeline:request": EmptyPayload,
    "keepsake:list": KeepsakeListPayload,
    "keepsake:add": KeepsakeAddPayload,
    "backup:export": EmptyPayload,
    "backup:import": BackupImportPayload,
    "image:random": ImageRandomPayload,
    "emotion:get": EmptyPayload,
    "persona:get": EmptyPayload,
    "persona:import": PersonaImportPayload,
    "persona:activate": PersonaActivatePayload,
    "relationship:get": EmptyPayload,
    "settings:update": SettingsUpdatePayload,
    "settings:get": EmptyPayload,
    "ai_usage:get": EmptyPayload,
    "ai_usage:grant": AIUsageGrantPayload,
    "ai_usage:revoke": AIUsageRevokePayload,
    "user:profile:get": EmptyPayload,
    "user:profile:update": UserProfileUpdatePayload,
    "anti_ai:status": EmptyPayload,
}

MUTATING_COMMAND_NAMES = frozenset(
    {
        "memory:candidates:confirm",
        "memory:candidates:reject",
        "memory:store",
        "memory:edit",
        "memory:delete",
        "group:send",
        "sticker:collect",
        "sticker:react",
        "game_state:put",
        "archive:put",
        "archive:migrate",
        "module:control",
        "keepsake:add",
        "persona:import",
        "persona:activate",
        "ai_usage:grant",
        "ai_usage:revoke",
        "backup:import",
        "settings:update",
        "user:profile:update",
    }
)

if frozenset(COMMAND_PAYLOAD_MODELS) != MVP_COMMAND_NAMES:
    raise RuntimeError("every MVP command must have exactly one payload contract")


class PersonaScopeV4(_ContractModel):
    persona_id: str = Field(min_length=1, max_length=128)
    epoch: int = Field(ge=1)
    fingerprint: str = Field(pattern=_FINGERPRINT_PATTERN.pattern)

    @field_validator("persona_id")
    @classmethod
    def validate_persona_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("persona_id contains unsupported characters")
        return value


class CommandEnvelopeV4(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    request_id: str = Field(default_factory=lambda: uuid4().hex)
    idempotency_key: str = Field(default_factory=lambda: uuid4().hex)
    command: str = Field(min_length=1, max_length=128)
    persona: PersonaScopeV4
    payload: dict[str, Any] = Field(default_factory=dict)
    causation_id: str | None = Field(default=None, max_length=128)
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, value: int) -> int:
        if value != PROTOCOL_VERSION:
            raise ValueError(f"unsupported protocol version: {value}")
        return value

    @field_validator("request_id", "idempotency_key")
    @classmethod
    def validate_identifier(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("identifier contains unsupported characters")
        return value

    @field_validator("command")
    @classmethod
    def validate_command(cls, value: str) -> str:
        if value not in MVP_COMMAND_NAMES:
            raise ValueError(f"unknown command: {value}")
        return value

    @model_validator(mode="after")
    def validate_payload_contract(self) -> "CommandEnvelopeV4":
        payload_model = COMMAND_PAYLOAD_MODELS[self.command]
        validated = payload_model.model_validate(self.payload)
        if (
            self.command == "chat:send"
            and validated.request_id is not None
            and validated.request_id != self.request_id
        ):
            raise ValueError("chat payload request_id does not match envelope")
        object.__setattr__(
            self,
            "payload",
            validated.model_dump(exclude_none=True),
        )
        return self


class DomainError(_ContractModel):
    code: ErrorCode
    message: str = Field(min_length=1, max_length=500)
    retryable: bool = False
    details: dict[str, Any] = Field(default_factory=dict)


class CommandResultV4(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    request_id: str
    ok: bool
    data: dict[str, Any] | list[Any] | str | int | float | bool | None = None
    error: DomainError | None = None

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, value: int) -> int:
        if value != PROTOCOL_VERSION:
            raise ValueError(f"unsupported protocol version: {value}")
        return value

    @classmethod
    def success(cls, request_id: str, data: Any = None) -> "CommandResultV4":
        return cls(request_id=request_id, ok=True, data=data)

    @classmethod
    def failure(
        cls,
        request_id: str,
        *,
        code: ErrorCode,
        message: str,
        retryable: bool = False,
        details: dict[str, Any] | None = None,
    ) -> "CommandResultV4":
        return cls(
            request_id=request_id,
            ok=False,
            error=DomainError(
                code=code,
                message=message,
                retryable=retryable,
                details=details or {},
            ),
        )

    def model_post_init(self, __context: Any) -> None:
        if self.ok and self.error is not None:
            raise ValueError("successful result cannot carry an error")
        if not self.ok and self.error is None:
            raise ValueError("failed result must carry an error")


class DomainEventV4(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    event_id: str = Field(default_factory=lambda: uuid4().hex)
    event_type: str = Field(min_length=1, max_length=128)
    persona: PersonaScopeV4
    payload: dict[str, Any] = Field(default_factory=dict)
    causation_id: str | None = Field(default=None, max_length=128)
    occurred_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    payload_version: int = Field(default=1, ge=1)

    @field_validator("event_id", "event_type")
    @classmethod
    def validate_identifier(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("event identifier contains unsupported characters")
        return value


class V3FrameAdapter:
    """Development-only compatibility boundary; production never downgrades."""

    legacy_protocol_version: ClassVar[int] = 3

    @staticmethod
    def to_v4(frame: dict[str, Any], persona: PersonaScopeV4) -> CommandEnvelopeV4:
        if not isinstance(frame, dict):
            raise TypeError("legacy frame must be an object")
        command = frame.get("type")
        payload = frame.get("payload", {})
        if not isinstance(command, str) or command not in MVP_COMMAND_NAMES:
            raise ValueError("legacy frame has an unknown command")
        if not isinstance(payload, dict):
            raise TypeError("legacy frame payload must be an object")
        request_id = str(frame.get("request_id") or uuid4().hex)
        idempotency_key = str(
            payload.get("idempotency_key")
            or payload.get("client_request_id")
            or request_id
        )
        return CommandEnvelopeV4(
            request_id=request_id,
            idempotency_key=idempotency_key,
            command=command,
            persona=persona,
            payload=payload,
        )

    @staticmethod
    def result_to_v3(
        result: CommandResultV4,
        *,
        response_type: str,
    ) -> dict[str, Any]:
        if result.ok:
            payload = result.data
        else:
            assert result.error is not None
            payload = {
                "ok": False,
                "error": {
                    "code": result.error.code.value,
                    "message": result.error.message,
                    "retryable": result.error.retryable,
                },
            }
        return {
            "type": response_type,
            "request_id": result.request_id,
            "payload": payload,
        }


# Internal source compatibility while the remaining modular-monolith classes
# are renamed independently. All aliases now enforce the V4 wire contract.
PersonaScopeV3 = PersonaScopeV4
CommandEnvelopeV3 = CommandEnvelopeV4
CommandResultV3 = CommandResultV4
DomainEventV3 = DomainEventV4
V2FrameAdapter = V3FrameAdapter


def public_error_message(error: BaseException) -> str:
    """Return a bounded message that cannot impersonate the companion."""

    code = str(getattr(error, "code", "") or "")
    known = {
        "REVERIE_SECURE_STORAGE_UNAVAILABLE": "系统安全凭据存储当前不可用。",
        "REVERIE_VAULT_CORRUPT": "本地凭据保险库无法解密，请先清理或恢复。",
        "REVERIE_VAULT_IO": "本地凭据保险库无法读写。",
    }
    return known.get(code, "请求未完成。技术详情已写入本地日志。")
