"""Canonical V4 command/result/event contracts.

This Python module is the only source of message names.  The checked-in
TypeScript client is generated by ``script/generate_protocol_contracts.py``.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
import json
import re
from typing import Any, ClassVar, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, RootModel, StrictBool, StrictInt, field_validator, model_validator


PROTOCOL_VERSION = 4
_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
_FINGERPRINT_PATTERN = re.compile(r"^[a-f0-9]{64}$")
_CANDIDATE_ID_PATTERN = re.compile(r"^mc_[a-f0-9]{32}$")


LEGACY_MESSAGE_TYPES: tuple[tuple[str, str], ...] = (
    ("CHAT_SEND", "chat:send"),
    ("CHAT_CANCEL", "chat:cancel"),
    ("CHAT_REVEAL", "chat:reveal"),
    ("CHAT_STOP", "chat:stop"),
    ("CHAT_HISTORY", "chat:history"),
    ("CHAT_MEDIA", "chat:media"),
    ("VIDEO_DOWNLOAD", "video:download"),
    ("BRIDGE_AUTH", "bridge:auth"),
    ("LOCAL_MODE_SET", "local_mode:set"),
    ("MEMORY_QUERY", "memory:query"),
    ("MEMORY_LIST", "memory:list"),
    ("MEMORY_EDIT", "memory:edit"),
    ("MEMORY_DELETE", "memory:delete"),
    ("MEMORY_SETTINGS_GET", "memory:settings:get"),
    ("MEMORY_STORE", "memory:store"),
    ("MEMORY_REINFORCE", "memory:reinforce"),
    ("MEMORY_CANDIDATE_LIST", "memory:candidates:list"),
    ("MEMORY_CANDIDATE_CONFIRM", "memory:candidates:confirm"),
    ("MEMORY_CANDIDATE_REJECT", "memory:candidates:reject"),
    ("EMOTION_GET", "emotion:get"),
    ("PERSONA_GET", "persona:get"),
    ("PERSONA_IMPORT", "persona:import"),
    ("PERSONA_ACTIVATE", "persona:activate"),
    ("ARCHIVE_GET", "archive:get"),
    ("ARCHIVE_PUT", "archive:put"),
    ("ARCHIVE_MIGRATE", "archive:migrate"),
    ("MODULE_LIST", "module:list"),
    ("MODULE_CONTROL", "module:control"),
    ("GAME_STATE_GET", "game_state:get"),
    ("GAME_STATE_PUT", "game_state:put"),
    ("GAME_MOVE", "game:move"),
    ("RELATIONSHIP_GET", "relationship:get"),
    ("DIARY_REQUEST", "diary:request"),
    ("DIARY_WRITE", "diary:write"),
    ("TIMELINE_REQUEST", "timeline:request"),
    ("AMBIENT_GET", "ambient:get"),
    ("API_BUDGET_GET", "api:budget:get"),
    ("GROUP_REQUEST", "group:request"),
    ("GROUP_SEND", "group:send"),
    ("IMAGE_RANDOM", "image:random"),
    ("TTS_LIST", "tts:list"),
    ("TTS_SYNTHESIZE", "tts:synthesize"),
    ("SETTINGS_UPDATE", "settings:update"),
    ("SETTINGS_GET", "settings:get"),
    ("AI_USAGE_GET", "ai_usage:get"),
    ("AI_USAGE_GRANT", "ai_usage:grant"),
    ("AI_USAGE_REVOKE", "ai_usage:revoke"),
    ("USER_PROFILE_GET", "user:profile:get"),
    ("USER_PROFILE_UPDATE", "user:profile:update"),
    ("KEEPSAKE_LIST", "keepsake:list"),
    ("KEEPSAKE_ADD", "keepsake:add"),
    ("BACKUP_EXPORT", "backup:export"),
    ("BACKUP_IMPORT", "backup:import"),
    ("STICKER_LIST", "sticker:list"),
    ("STICKER_COLLECT", "sticker:collect"),
    ("STICKER_REACT", "sticker:react"),
    ("STICKER_IMPORT", "sticker:import"),
    ("ANTI_AI_STATUS", "anti_ai:status"),
    ("IMMERSION_NEARBY", "immersion:nearby"),
    ("IMMERSION_CLOSEUP", "immersion:closeup"),
    ("IMMERSION_SMART_HOME", "immersion:smart_home"),
    ("CHAT_CHUNK", "chat:chunk"),
    ("CHAT_BUBBLE", "chat:bubble"),
    ("CHAT_DONE", "chat:done"),
    ("CHAT_TYPING", "chat:typing"),
    ("CHAT_STATE", "chat:state"),
    ("CHAT_ERROR", "chat:error"),
    ("CHAT_RETRACT", "chat:retract"),
    ("CHAT_HISTORY_RESULT", "chat:history:result"),
    ("CHAT_MEDIA_RESULT", "chat:media:result"),
    ("VIDEO_DOWNLOAD_RESULT", "video:download:result"),
    ("VIDEO_DOWNLOAD_PROGRESS", "video:download:progress"),
    ("BRIDGE_AUTH_OK", "bridge:auth_ok"),
    ("BRIDGE_AUTH_ERROR", "bridge:auth_error"),
    ("LOCAL_MODE_STATE", "local_mode:state"),
    ("PROACTIVE_MESSAGE", "proactive:message"),
    ("PROACTIVE_NOTIFY", "proactive:notify"),
    ("EMOTION_UPDATE", "emotion:update"),
    ("MEMORY_RESULT", "memory:result"),
    ("MEMORY_SETTINGS_RESULT", "memory:settings:result"),
    ("MEMORY_CANDIDATE_RESULT", "memory:candidates:result"),
    ("PERSONA_DATA", "persona:data"),
    ("PERSONA_IMPORT_RESULT", "persona:import:result"),
    ("ARCHIVE_RESULT", "archive:result"),
    ("MODULE_RESULT", "module:result"),
    ("GAME_STATE_RESULT", "game_state:result"),
    ("GAME_MOVE_RESULT", "game:move:result"),
    ("RELATIONSHIP_DATA", "relationship:data"),
    ("DIARY_RESULT", "diary:result"),
    ("TIMELINE_RESULT", "timeline:result"),
    ("AMBIENT_RESULT", "ambient:result"),
    ("API_BUDGET_RESULT", "api:budget:result"),
    ("GROUP_RESULT", "group:result"),
    ("IMAGE_RESULT", "image:result"),
    ("TTS_RESULT", "tts:result"),
    ("USER_PROFILE_RESULT", "user:profile:result"),
    ("KEEPSAKE_RESULT", "keepsake:result"),
    ("BACKUP_RESULT", "backup:result"),
    ("SETTINGS_UPDATE_RESULT", "settings:update:result"),
    ("SETTINGS_GET_RESULT", "settings:get:result"),
    ("AI_USAGE_RESULT", "ai_usage:result"),
    ("RUNTIME_ACTIVITY", "runtime:activity"),
    ("STICKER_DATA", "sticker:data"),
    ("ANTI_AI_STATUS_RESULT", "anti_ai:status:result"),
    ("IMMERSION_RESULT", "immersion:result"),
    ("ERROR", "error"),
    ("HEARTBEAT", "heartbeat"),
)

MVP_COMMAND_NAMES = frozenset(
    value
    for name, value in LEGACY_MESSAGE_TYPES
    if name
    in {
        "CHAT_SEND",
        "CHAT_CANCEL",
        "CHAT_STOP",
        "CHAT_REVEAL",
        "CHAT_HISTORY",
        "CHAT_MEDIA",
        "VIDEO_DOWNLOAD",
        "MEMORY_QUERY",
        "MEMORY_LIST",
        "MEMORY_STORE",
        "MEMORY_REINFORCE",
        "MEMORY_EDIT",
        "MEMORY_DELETE",
        "MEMORY_SETTINGS_GET",
        "MEMORY_CANDIDATE_LIST",
        "MEMORY_CANDIDATE_CONFIRM",
        "MEMORY_CANDIDATE_REJECT",
        "GROUP_REQUEST",
        "GROUP_SEND",
        "STICKER_LIST",
        "STICKER_COLLECT",
        "STICKER_REACT",
        "STICKER_IMPORT",
        "GAME_STATE_GET",
        "GAME_STATE_PUT",
        "GAME_MOVE",
        "IMMERSION_NEARBY",
        "IMMERSION_CLOSEUP",
        "IMMERSION_SMART_HOME",
        "AMBIENT_GET",
        "API_BUDGET_GET",
        "ARCHIVE_GET",
        "ARCHIVE_PUT",
        "ARCHIVE_MIGRATE",
        "MODULE_LIST",
        "MODULE_CONTROL",
        "DIARY_REQUEST",
        "DIARY_WRITE",
        "TIMELINE_REQUEST",
        "KEEPSAKE_LIST",
        "KEEPSAKE_ADD",
        "BACKUP_EXPORT",
        "BACKUP_IMPORT",
        "IMAGE_RANDOM",
        "EMOTION_GET",
        "TTS_LIST",
        "TTS_SYNTHESIZE",
        "PERSONA_GET",
        "PERSONA_IMPORT",
        "PERSONA_ACTIVATE",
        "RELATIONSHIP_GET",
        "SETTINGS_UPDATE",
        "SETTINGS_GET",
        "AI_USAGE_GET",
        "AI_USAGE_GRANT",
        "AI_USAGE_REVOKE",
        "USER_PROFILE_GET",
        "USER_PROFILE_UPDATE",
        "ANTI_AI_STATUS",
    }
)
MVP_EVENT_NAMES = frozenset(
    value
    for name, value in LEGACY_MESSAGE_TYPES
    if name
    in {
        "CHAT_CHUNK",
        "CHAT_BUBBLE",
        "CHAT_DONE",
        "CHAT_TYPING",
        "CHAT_STATE",
        "CHAT_ERROR",
        "CHAT_RETRACT",
        "CHAT_HISTORY_RESULT",
        "CHAT_MEDIA_RESULT",
        "VIDEO_DOWNLOAD_RESULT",
        "VIDEO_DOWNLOAD_PROGRESS",
        "EMOTION_UPDATE",
        "MEMORY_RESULT",
        "MEMORY_SETTINGS_RESULT",
        "MEMORY_CANDIDATE_RESULT",
        "GROUP_RESULT",
        "STICKER_DATA",
        "GAME_STATE_RESULT",
        "GAME_MOVE_RESULT",
        "IMMERSION_RESULT",
        "AMBIENT_RESULT",
        "API_BUDGET_RESULT",
        "ARCHIVE_RESULT",
        "MODULE_RESULT",
        "DIARY_RESULT",
        "TIMELINE_RESULT",
        "KEEPSAKE_RESULT",
        "BACKUP_RESULT",
        "IMAGE_RESULT",
        "TTS_RESULT",
        "PROACTIVE_MESSAGE",
        "RUNTIME_ACTIVITY",
        "PERSONA_DATA",
        "PERSONA_IMPORT_RESULT",
        "AI_USAGE_RESULT",
        "RELATIONSHIP_DATA",
        "USER_PROFILE_RESULT",
        "SETTINGS_UPDATE_RESULT",
        "SETTINGS_GET_RESULT",
        "ANTI_AI_STATUS_RESULT",
        "ERROR",
        "HEARTBEAT",
    }
)
# Compatibility import name for callers which only need the production
# allowlist. V4 intentionally does not expose retired feature commands.
COMMAND_NAMES = MVP_COMMAND_NAMES


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    STALE_PERSONA = "STALE_PERSONA"
    MODULE_UNAVAILABLE = "MODULE_UNAVAILABLE"
    MODULE_DEGRADED = "MODULE_DEGRADED"
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    LOCAL_MODE_BLOCKED = "LOCAL_MODE_BLOCKED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_OUTCOME_UNKNOWN = "PROVIDER_OUTCOME_UNKNOWN"
    CONFLICT = "CONFLICT"
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    INTERNAL = "INTERNAL"


class _ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class _PayloadModel(BaseModel):
    """Strict command payload parsed again at the trusted Python boundary."""

    model_config = ConfigDict(extra="forbid", frozen=True)


class EmptyPayload(_PayloadModel):
    pass


class ChatSendPayload(_PayloadModel):
    text: str = Field(min_length=1, max_length=20_000)
    request_id: str | None = Field(default=None, max_length=128)
    conversation_id: str = Field(default="dream-room", min_length=1, max_length=160)
    sent_at_utc: str | None = Field(default=None, max_length=64)
    # Optional chat image attachment. The renderer either hands over a local
    # absolute path from an Electron file dialog (preferred — keeps big base64
    # out of the bridge frame) or a compressed data URL from clipboard paste.
    image_path: str | None = Field(default=None, max_length=1_024)
    image_data_url: str | None = Field(default=None, max_length=350_000)
    # Optional video attachment: the sha256 media id of a video already stored
    # by the video:download pipeline. A video can be hundreds of MB, so it is
    # never inlined as a data URL — it is downloaded, merged and stored
    # server-side first, then referenced here by id (mirrors how images end up
    # content-addressed, but without any re-encoding).
    video_media_id: str | None = Field(default=None, max_length=128)
    sticker: "StickerAttachmentPayload | None" = None

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str | None) -> str | None:
        if value is not None and not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value

    @field_validator("conversation_id")
    @classmethod
    def validate_conversation_id(cls, value: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9._:-]{1,160}", value):
            raise ValueError("conversation_id contains unsupported characters")
        return value

    @field_validator("image_path")
    @classmethod
    def validate_image_path(cls, value: str | None) -> str | None:
        if value is None:
            return value
        if "\x00" in value or any(ord(char) < 32 for char in value):
            raise ValueError("image_path contains control characters")
        if not re.fullmatch(r"([A-Za-z]:[\\/].*|/.+)", value, re.DOTALL):
            raise ValueError("image_path must be an absolute local path")
        return value

    @field_validator("image_data_url")
    @classmethod
    def validate_image_data_url(cls, value: str | None) -> str | None:
        if value is None:
            return value
        if not re.fullmatch(
            r"data:image/(?:png|jpeg|jpg|webp|gif);base64,[A-Za-z0-9+/=\r\n]+",
            value,
        ):
            raise ValueError("image_data_url must be a base64 image data URL")
        return value

    @field_validator("video_media_id")
    @classmethod
    def validate_video_media_id(cls, value: str | None) -> str | None:
        if value is None:
            return value
        if not re.fullmatch(r"[A-Fa-f0-9]{64}", value):
            raise ValueError("video_media_id must be a sha256 hex id")
        return value


class StickerAttachmentPayload(_PayloadModel):
    """Sticker object the renderer may attach to a chat:send turn."""

    id: str | None = Field(default=None, max_length=128)
    text: str = Field(default="", max_length=400)
    emotions: list[str] = Field(default_factory=list, max_length=24)
    style_tags: list[str] = Field(default_factory=list, max_length=24)
    image_data_url: str | None = Field(default=None, max_length=350_000)
    source: str | None = Field(default=None, max_length=40)


class ChatMediaPayload(_PayloadModel):
    """Fetch one persisted chat media attachment as a data URL."""

    media_id: str = Field(min_length=1, max_length=128)

    @field_validator("media_id")
    @classmethod
    def validate_media_id(cls, value: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9._-]{1,128}", value):
            raise ValueError("media_id contains unsupported characters")
        return value


class VideoDownloadPayload(_PayloadModel):
    """Download a video (HLS m3u8 or direct mp4/webm) and store it locally.

    The feature is disclaimer-gated: the bridge refuses this command unless the
    user has enabled ``video_download`` and acknowledged the liability
    disclaimer. ``source_url`` is validated as a public http(s) URL by the
    download kernel's SSRF gate; ``page_title`` is an optional label carried
    only for the chat message caption.
    """

    source_url: str = Field(min_length=1, max_length=2_048)
    request_id: str | None = Field(default=None, max_length=128)
    conversation_id: str = Field(default="dream-room", min_length=1, max_length=160)
    page_title: str | None = Field(default=None, max_length=400)

    @field_validator("source_url")
    @classmethod
    def validate_source_url(cls, value: str) -> str:
        if not re.fullmatch(r"https?://[^\s]{1,2040}", value):
            raise ValueError("source_url must be an http(s) URL")
        return value

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str | None) -> str | None:
        if value is not None and not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value

    @field_validator("conversation_id")
    @classmethod
    def validate_conversation_id(cls, value: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9._:-]{1,160}", value):
            raise ValueError("conversation_id contains unsupported characters")
        return value


class GameMovePayload(_PayloadModel):
    """Ask the companion to choose the next move in a local board game.

    ``state`` is the renderer's authoritative board serialization; Python
    never mutates it — it only feeds the persona prompt and returns a raw
    move candidate plus an in-character comment. Legality is enforced by the
    renderer's rules engine.
    """

    game: str = Field(min_length=1, max_length=20)
    state: dict[str, Any]

    @field_validator("game")
    @classmethod
    def validate_game(cls, value: str) -> str:
        if not re.fullmatch(r"[a-z0-9_-]{1,20}", value):
            raise ValueError("game contains unsupported characters")
        return value

    @model_validator(mode="after")
    def validate_state_size(self) -> "GameMovePayload":
        serialized = json.dumps(self.state, ensure_ascii=False, default=str)
        if len(serialized) > 100_000:
            raise ValueError("game state is too large")
        return self


class StickerImportPayload(_PayloadModel):
    """Import a local image file as a user sticker via an Electron dialog."""

    file_path: str = Field(min_length=1, max_length=1_024)
    style_tags: list[str] = Field(default_factory=list, max_length=24)

    @field_validator("file_path")
    @classmethod
    def validate_file_path(cls, value: str) -> str:
        if "\x00" in value or any(ord(char) < 32 for char in value):
            raise ValueError("file_path contains control characters")
        if not re.fullmatch(r"([A-Za-z]:[\\/].*|/.+)", value, re.DOTALL):
            raise ValueError("file_path must be an absolute local path")
        return value


class ChatTargetPayload(_PayloadModel):
    request_id: str = Field(min_length=1, max_length=128)

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value


class ChatStopPayload(_PayloadModel):
    """Legacy stop alias.

    ``request_id`` is optional because ``handle_chat_stop`` answers with a
    dedicated ERROR frame instead of a generic validation failure when the
    controller does not name a specific request (global cancellation is
    forbidden by design).
    """

    request_id: str | None = Field(default=None, max_length=128)

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, value: str | None) -> str | None:
        if value is not None and not _ID_PATTERN.fullmatch(value):
            raise ValueError("request_id contains unsupported characters")
        return value


class AIUsageGrantPayload(_PayloadModel):
    """Per-feature consent grant. Booleans must be exactly ``True`` to mirror
    the bridge handler's ``is not True`` checks (no truthy coercion)."""

    model_config = ConfigDict(strict=True, extra="forbid", frozen=True)

    feature: str = Field(min_length=1, max_length=80)
    consent_digest: str = Field(min_length=1, max_length=128)
    api_cost_acknowledged: StrictBool
    user_confirmed: StrictBool

    @field_validator("api_cost_acknowledged", "user_confirmed")
    @classmethod
    def must_be_true(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("explicit confirmation must be exactly true")
        return value


class AIUsageRevokePayload(_PayloadModel):
    feature: str = Field(min_length=1, max_length=80)


class PersonaImportPayload(_PayloadModel):
    """Untrusted SillyTavern JSON card; the importer re-validates size/depth.

    The wire field is ``json``; the attribute is ``json_text`` (serialized
    back as ``json`` via the alias) to avoid shadowing pydantic's historical
    ``json`` helper attribute.
    """

    model_config = ConfigDict(serialize_by_alias=True, extra="forbid", frozen=True)

    json_text: str = Field(
        alias="json",
        validation_alias="json",
        min_length=1,
        max_length=2_000_000,
    )
    filename: str = Field(default="character.json", min_length=1, max_length=256)
    identity_change_confirmed: StrictBool | None = None
    actor: Literal["owner", "local_admin"] | None = None
    reason: str | None = Field(default=None, min_length=3, max_length=500)


class PersonaActivatePayload(_PayloadModel):
    """Explicit identity switch. ``expected_persona_*`` is injected by the
    bridge from the active scope, not part of the client contract."""

    model_config = ConfigDict(strict=True, extra="forbid", frozen=True)

    profile_id: str = Field(min_length=1, max_length=160)
    identity_change_confirmed: StrictBool
    confirmed_profile_id: str = Field(min_length=1, max_length=160)
    actor: Literal["owner", "local_admin"]
    reason: str = Field(min_length=3, max_length=500)

    @field_validator("identity_change_confirmed")
    @classmethod
    def must_be_true(cls, value: bool) -> bool:
        if value is not True:
            raise ValueError("identity change confirmation must be exactly true")
        return value


class KeepsakeAddPayload(_PayloadModel):
    kind: str = Field(default="text", min_length=1, max_length=40)
    title: str = Field(default="", max_length=80)
    content: str = Field(default="", max_length=1200)
    source_path: str = Field(default="", max_length=1000)
    media_data_url: str = Field(default="", max_length=2_097_152)
    tags: list[str] = Field(default_factory=list, max_length=50)
    importance: float = Field(default=0.5, ge=0.0, le=1.0)


class ArchivePutPayload(_PayloadModel):
    """Archive write; deep validation happens in the archive store."""

    archive: dict[str, Any] = Field(default_factory=dict)
    expected_revision: StrictInt = Field(default=0, ge=0)


class ModuleControlPayload(_PayloadModel):
    module_id: str = Field(min_length=1, max_length=64, pattern=r"^[a-z][a-z0-9._-]{0,63}$")
    action: str = Field(min_length=1, max_length=32)


class ChatHistoryCursor(_PayloadModel):
    sequence: int = Field(ge=1)


class ChatHistoryPayload(_PayloadModel):
    conversation_id: str = Field(default="dream-room", min_length=1, max_length=160)
    limit: int = Field(default=300, ge=1, le=300)
    before: ChatHistoryCursor | None = None

    @field_validator("conversation_id")
    @classmethod
    def validate_conversation_id(cls, value: str) -> str:
        if not re.fullmatch(r"[A-Za-z0-9._:-]{1,160}", value):
            raise ValueError("conversation_id contains unsupported characters")
        return value


class MemoryQueryPayload(_PayloadModel):
    query: str = Field(min_length=1, max_length=2_000)
    top_k: int = Field(default=10, ge=1, le=50)


class MemoryListPayload(_PayloadModel):
    limit: int = Field(default=100, ge=1, le=200)


class MemoryTargetPayload(_PayloadModel):
    memory_id: str = Field(min_length=1, max_length=128)

    @field_validator("memory_id")
    @classmethod
    def validate_memory_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("memory_id contains unsupported characters")
        return value


class StandardMemoryStorePayload(_PayloadModel):
    """Store a user-selected chat record in a memory layer.

    ``permanent`` marks a precious memory (never decays, never confused);
    ``long_term``/``short_term`` remain forgettable.
    """

    text: str = Field(default="", max_length=2_000)
    layer: Literal["long_term", "short_term", "permanent"] = "long_term"
    preference: Literal["place", "category"] | None = None
    display_label: str = Field(default="", max_length=120)
    broad_category: str = Field(default="", max_length=80)
    user_confirmed: StrictBool = False

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        return value.strip()

    @model_validator(mode="after")
    def validate_explicit_preference(self) -> "StandardMemoryStorePayload":
        if self.preference is None:
            if not self.text:
                raise ValueError("memory text cannot be blank")
            if self.display_label or self.broad_category or self.user_confirmed:
                raise ValueError("preference fields require a preference kind")
            return self
        if self.user_confirmed is not True:
            raise ValueError("place preference requires explicit confirmation")
        if self.text:
            raise ValueError("place preference text is constructed by the trusted host")
        if self.preference == "place" and (not self.display_label or self.broad_category):
            raise ValueError("place preference requires only a display label")
        if self.preference == "category" and (not self.broad_category or self.display_label):
            raise ValueError("category preference requires only a broad category")
        return self


class CoarseSystemLocationMemoryPayload(_PayloadModel):
    kind: Literal["coarse_system_location"]
    neighborhood_scale: Literal["neighborhood-scale", "city-scale", "regional-scale"]
    user_confirmed: Literal[True]


class MemoryStorePayload(RootModel[StandardMemoryStorePayload | CoarseSystemLocationMemoryPayload]):
    """Strict union for normal memories and separately confirmed OS scale summaries."""


class MemoryEditPayload(MemoryTargetPayload):
    text: str = Field(min_length=1, max_length=2_000)

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("memory correction cannot be blank")
        return cleaned


class MemoryReinforcePayload(MemoryTargetPayload):
    """Manual weaken/strengthen/reactivate/pin adjustments from the memory UI."""

    op: Literal["weaken", "strengthen", "reactivate", "pin", "unpin"]
    amount: float | None = Field(default=None, gt=0.0, le=0.5)


class MemoryCandidateListPayload(_PayloadModel):
    status: Literal["pending", "confirmed", "rejected", "all"] = "pending"
    limit: int = Field(default=100, ge=1, le=200)


class MemoryCandidateDecisionPayload(_PayloadModel):
    candidate_id: str = Field(pattern=_CANDIDATE_ID_PATTERN.pattern)


class GroupSendPayload(_PayloadModel):
    """Send one message into the local role-world group chat."""

    text: str = Field(min_length=1, max_length=2_000)
    thread_id: str = Field(default="local-friends", min_length=1, max_length=120)
    user_name: str = Field(default="你", min_length=1, max_length=40)

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("group message cannot be blank")
        return cleaned


class StickerListPayload(_PayloadModel):
    """List user-collected and default stickers."""

    limit: int = Field(default=100, ge=1, le=200)


class StickerCollectPayload(_PayloadModel):
    """Collect a user-provided sticker image or text with emotion/style tags."""

    text: str = Field(default="", max_length=400)
    emotions: list[str] = Field(default_factory=list, max_length=24)
    style_tags: list[str] = Field(default_factory=list, max_length=24)
    image_data_url: str = Field(default="", max_length=16_000_000)


class StickerReactPayload(_PayloadModel):
    """Record user feedback for sticker reuse preferences."""

    id: str = Field(min_length=1, max_length=128)
    liked: bool = True


class GameStateGetPayload(_PayloadModel):
    """Read persisted state for one local mini-game."""

    game_id: str = Field(min_length=1, max_length=64, pattern=r"^[a-z][a-z0-9._-]{0,63}$")


class GameStatePutPayload(GameStateGetPayload):
    """Persist bounded state for one local mini-game."""

    state: dict[str, Any] = Field(default_factory=dict)
    expected_revision: int = Field(default=0, ge=0, le=1_000_000)


class ImmersionNearbyPayload(_PayloadModel):
    """Request nearby life context from a user-granted coarse location."""

    latitude: float = Field(ge=-90.0, le=90.0)
    longitude: float = Field(ge=-180.0, le=180.0)
    place_types: list[str] = Field(default_factory=list, max_length=6)
    radius_m: int = Field(default=1200, ge=300, le=5000)

    @field_validator("place_types")
    @classmethod
    def validate_place_types(cls, value: list[str]) -> list[str]:
        allowed = {"restaurant", "shop", "cafe", "supermarket", "park", "mall"}
        seen: list[str] = []
        for item in value:
            kind = str(item).strip().lower()
            if kind in allowed and kind not in seen:
                seen.append(kind)
        return seen


class ImmersionCloseupPayload(_PayloadModel):
    """Request a multimodal close-up generation plan."""

    kind: Literal["meal", "cooking", "bath", "shopping"] = "meal"


class ImmersionSmartHomePayload(_PayloadModel):
    """Issue a safe dry-run smart-home command envelope."""

    provider: Literal["manual", "xiaomi", "huawei"] = "manual"
    device: str = Field(min_length=1, max_length=40)
    action: str = Field(min_length=1, max_length=80)


class DiaryRequestPayload(_PayloadModel):
    """Request diary data; optional unlock_key action for the easter egg."""

    action: Literal["list", "read", "unlock_key"] = "list"
    date: str = Field(default="", max_length=32)
    host_date: str = Field(default="", max_length=32)


class KeepsakeListPayload(_PayloadModel):
    """List collected keepsakes."""

    limit: int = Field(default=20, ge=1, le=200)


class BackupImportPayload(_PayloadModel):
    """Restore the complete local memory state from a JSON-safe payload."""

    backup: dict[str, Any] = Field(default_factory=dict)


class ImageRandomPayload(_PayloadModel):
    """Request a random image from the optional local image service."""

    mode: Literal["sfw", "nsfw", "random"] = "sfw"


class TTSSynthesizePayload(_PayloadModel):
    """Synthesize speech audio for a text chunk via the active TTS provider."""

    text: str = Field(min_length=1, max_length=5000)
    voice: str | None = Field(default=None, max_length=64)
    provider: str | None = Field(default=None, max_length=32)


class SettingsUpdatePayload(_PayloadModel):
    """Live settings surface. Extra keys stay forbidden; the allow-list matches
    ``handle_settings_update`` rather than the historical MVP subset."""

    section: Literal[
        "onboarding", "memory", "chat", "personality", "features",
        "immersion", "tts", "ui", "persona_prompt_opts",
    ]
    completed: bool | None = None
    onboarding_version: int | None = Field(default=None, ge=0, le=100)
    onboarding_state: Literal[
        "not_started", "in_progress", "committing", "complete"
    ] | None = None
    onboarding_last_step: Literal[
        "welcome", "mode", "profile", "deepseek", "optional-media",
        "features", "rooms", "cards", "location", "pet", "finish",
    ] | None = None
    experience_mode: Literal["full", "core"] | None = None
    mode: Literal["mvp", "dream"] | None = None

    tts_enabled: bool | None = None
    tts_provider: Literal["gemini", "openai", "gpt-sovits"] | None = None
    tts_voice: str | None = Field(default=None, max_length=64)
    tts_model: str | None = Field(default=None, max_length=128)
    tts_base_url: str | None = Field(default=None, max_length=128)

    retention_days: Literal[365, 730, 1095] | None = None
    forgetting_enabled: bool | None = None
    long_term_forgetting_enabled: bool | None = None
    short_term_forgetting_enabled: bool | None = None
    long_term_forget_days: int | None = Field(default=None, ge=60, le=365)
    short_term_forget_days: int | None = Field(default=None, ge=1, le=59)
    long_term_forget_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    short_term_forget_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    decay_lambda: float | None = Field(default=None, ge=0.0001, le=0.10)
    recall_reinforcement_alpha: float | None = Field(default=None, ge=0.0, le=0.50)
    minimum_retrieval_retention: float | None = Field(default=None, ge=0.0, le=0.95)
    embedding_model: str | None = Field(default=None, min_length=1, max_length=200)
    vector_quantization: Literal["float32", "int8"] | None = None
    vector_partitioning_enabled: bool | None = None
    memory_lifecycle_governance_enabled: bool | None = None
    memory_long_budget_chars: int | None = Field(default=None, ge=50_000, le=2_000_000)
    misremembering_enabled: bool | None = None
    long_term_misremembering_enabled: bool | None = None
    short_term_misremembering_enabled: bool | None = None
    misremember_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    long_term_misremember_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    short_term_misremember_probability: float | None = Field(default=None, ge=0.01, le=0.10)
    autonomous_memory_enabled: bool | None = None
    autonomous_memory_llm_enabled: bool | None = None
    self_growth_enabled: bool | None = None
    self_growth_from_web_enabled: bool | None = None
    self_growth_from_memory_enabled: bool | None = None
    self_growth_interval_days: int | None = Field(default=None, ge=30, le=365)

    reply_delay_min: float | None = Field(default=None, ge=1.0, le=60.0)
    reply_delay_max: float | None = Field(default=None, ge=1.0, le=60.0)
    split_messages: bool | None = None
    typing_indicator: bool | None = None
    allow_environment_description: bool | None = None
    status: Literal["online", "busy", "away", "sleeping"] | None = None

    personality_flaws_enabled: bool | None = None
    personality_flaws_disclaimer_acknowledged: bool | None = None
    user_selected_flaws: str | None = Field(default=None, max_length=400)
    emotion_system_enabled: bool | None = None
    emotion_carryover_days: int | None = Field(default=None, ge=1, le=7)
    emotion_inertia_factor: float | None = Field(default=None, ge=0.01, le=0.60)
    world_life_enabled: bool | None = None
    timeline_enabled: bool | None = None
    timeline_visuals_enabled: bool | None = None
    group_social_enabled: bool | None = None
    group_social_permanent_memory_enabled: bool | None = None
    group_social_api_replies_enabled: bool | None = None
    group_social_comment_probability: float | None = Field(default=None, ge=0.0, le=1.0)
    group_social_backchannel_probability: float | None = Field(default=None, ge=0.0, le=0.5)
    group_social_max_api_calls_per_action: int | None = Field(default=None, ge=0, le=3)
    proactive_event_stories_enabled: bool | None = None
    web_surfing_enabled: bool | None = None
    web_disclaimer_acknowledged: bool | None = None
    web_native_search_enabled: bool | None = None
    surf_keyless_search_enabled: bool | None = None
    web_allowed_topics: list[str] | None = Field(default=None, max_length=32)
    web_search_windows: list[str] | None = Field(default=None, max_length=24)
    web_refresh_interval_minutes: int | None = Field(default=None, ge=30, le=1440)
    keepsake_collection_enabled: bool | None = None
    keepsake_recall_probability: float | None = Field(default=None, ge=0.01, le=0.30)
    ambient_presence_enabled: bool | None = None
    ambient_book_pages_per_hour: float | None = Field(default=None, ge=0.1, le=12.0)
    ambient_trace_interval_minutes: int | None = Field(default=None, ge=30, le=1440)
    ambient_offline_replay_max_days: int | None = Field(default=None, ge=1, le=90)
    ambient_sticky_notes_enabled: bool | None = None
    thought_of_you_enabled: bool | None = None
    thought_share_probability: float | None = Field(default=None, ge=0.0, le=1.0)
    thought_min_delay_minutes: int | None = Field(default=None, ge=30, le=4320)
    thought_max_delay_minutes: int | None = Field(default=None, ge=60, le=10080)
    thought_share_start_hour: int | None = Field(default=None, ge=0, le=23)
    thought_share_end_hour: int | None = Field(default=None, ge=1, le=24)
    diary_key_easter_egg_enabled: bool | None = None
    diary_key_intimacy_threshold: int | None = Field(default=None, ge=100, le=10000)
    diary_key_happy_days: int | None = Field(default=None, ge=3, le=30)
    diary_key_private_emotion_threshold: float | None = Field(default=None, ge=40.0, le=95.0)
    user_phrase_alignment_enabled: bool | None = None
    user_phrase_alignment_probability: float | None = Field(default=None, ge=0.0, le=0.20)
    user_phrase_min_count: int | None = Field(default=None, ge=2, le=20)
    local_care_reflex_probability: float | None = Field(default=None, ge=0.0, le=1.0)
    api_budget_tracking_enabled: bool | None = None
    api_background_budget_enforced: bool | None = None
    api_background_daily_request_budget: int | None = Field(default=None, ge=1, le=10000)
    api_background_daily_token_budget: int | None = Field(default=None, ge=1000, le=10_000_000)

    proactive_chat_enabled: bool | None = None
    proactive_notifications_enabled: bool | None = None
    proactive_daily_limit: int | None = Field(default=None, ge=1, le=12)
    proactive_min_interval_minutes: int | None = Field(default=None, ge=15, le=1440)
    proactive_wake_min_minutes: int | None = Field(default=None, ge=2, le=60)
    proactive_wake_max_minutes: int | None = Field(default=None, ge=2, le=60)

    diary_enabled: bool | None = None
    diary_privacy_enabled: bool | None = None
    diary_peek_enabled: bool | None = None
    late_night_enabled: bool | None = None
    late_night_message_enabled: bool | None = None
    late_night_probability: float | None = Field(default=None, ge=0.01, le=0.30)
    video_download_enabled: bool | None = None
    video_download_disclaimer_acknowledged: bool | None = None
    video_max_size_mb: int | None = Field(default=None, ge=1, le=4096)
    video_max_duration_seconds: int | None = Field(default=None, ge=1, le=21600)
    video_total_quota_mb: int | None = Field(default=None, ge=1, le=51200)

    use_imported_system_prompt: bool | None = None
    use_imported_post_history_instructions: bool | None = None

    immersion_location_enabled: bool | None = None
    immersion_closeups_enabled: bool | None = None
    immersion_smart_home_enabled: bool | None = None
    immersion_location_radius_m: int | None = Field(default=None, ge=300, le=5000)

    @field_validator("web_search_windows", mode="before")
    @classmethod
    def _split_web_search_windows(cls, value: object) -> object:
        if isinstance(value, str):
            parts = value.replace("，", ",").replace("、", ",").split(",")
            return [item.strip() for item in parts if item.strip()]
        return value

    @field_validator("web_allowed_topics", mode="before")
    @classmethod
    def _split_web_allowed_topics(cls, value: object) -> object:
        if isinstance(value, str):
            parts = value.replace("，", "、").replace(",", "、").split("、")
            return [item.strip() for item in parts if item.strip()]
        return value

    @field_validator("embedding_model")
    @classmethod
    def _embedding_model_is_printable(cls, value: str | None) -> str | None:
        if value is None:
            return value
        cleaned = value.strip()
        if not cleaned or any(ord(char) < 32 for char in cleaned):
            raise ValueError("embedding_model is invalid")
        return cleaned

    @model_validator(mode="after")
    def validate_section_fields(self) -> "SettingsUpdatePayload":
        allowed = {
            "onboarding": {
                "section",
                "completed",
                "onboarding_version",
                "onboarding_state",
                "onboarding_last_step",
                "experience_mode",
            },
            "memory": {
                "section",
                "retention_days",
                "forgetting_enabled",
                "long_term_forgetting_enabled",
                "short_term_forgetting_enabled",
                "long_term_forget_days",
                "short_term_forget_days",
                "long_term_forget_probability",
                "short_term_forget_probability",
                "decay_lambda",
                "recall_reinforcement_alpha",
                "minimum_retrieval_retention",
                "embedding_model",
                "vector_quantization",
                "vector_partitioning_enabled",
                "memory_lifecycle_governance_enabled",
                "memory_long_budget_chars",
                "misremembering_enabled",
                "long_term_misremembering_enabled",
                "short_term_misremembering_enabled",
                "misremember_probability",
                "long_term_misremember_probability",
                "short_term_misremember_probability",
                "autonomous_memory_enabled",
                "autonomous_memory_llm_enabled",
                "self_growth_enabled",
                "self_growth_from_web_enabled",
                "self_growth_from_memory_enabled",
                "self_growth_interval_days",
            },
            "chat": {
                "section",
                "reply_delay_min",
                "reply_delay_max",
                "split_messages",
                "typing_indicator",
                "allow_environment_description",
                "status",
            },
            "personality": {
                "section",
                "personality_flaws_enabled",
                "personality_flaws_disclaimer_acknowledged",
                "user_selected_flaws",
                "emotion_system_enabled",
                "emotion_carryover_days",
                "emotion_inertia_factor",
                "world_life_enabled",
                "timeline_enabled",
                "timeline_visuals_enabled",
                "group_social_enabled",
                "group_social_permanent_memory_enabled",
                "group_social_api_replies_enabled",
                "group_social_comment_probability",
                "group_social_backchannel_probability",
                "group_social_max_api_calls_per_action",
                "proactive_chat_enabled",
                "proactive_notifications_enabled",
                "proactive_event_stories_enabled",
                "proactive_daily_limit",
                "proactive_min_interval_minutes",
                "proactive_wake_min_minutes",
                "proactive_wake_max_minutes",
                "web_surfing_enabled",
                "web_disclaimer_acknowledged",
                "web_native_search_enabled",
                "surf_keyless_search_enabled",
                "web_allowed_topics",
                "web_search_windows",
                "web_refresh_interval_minutes",
                "keepsake_collection_enabled",
                "keepsake_recall_probability",
                "ambient_presence_enabled",
                "ambient_book_pages_per_hour",
                "ambient_trace_interval_minutes",
                "ambient_offline_replay_max_days",
                "ambient_sticky_notes_enabled",
                "thought_of_you_enabled",
                "thought_share_probability",
                "thought_min_delay_minutes",
                "thought_max_delay_minutes",
                "thought_share_start_hour",
                "thought_share_end_hour",
                "diary_key_easter_egg_enabled",
                "diary_key_intimacy_threshold",
                "diary_key_happy_days",
                "diary_key_private_emotion_threshold",
                "user_phrase_alignment_enabled",
                "user_phrase_alignment_probability",
                "user_phrase_min_count",
                "local_care_reflex_probability",
                "api_budget_tracking_enabled",
                "api_background_budget_enforced",
                "api_background_daily_request_budget",
                "api_background_daily_token_budget",
            },
            "features": {
                "section",
                "proactive_chat_enabled",
                "proactive_notifications_enabled",
                "proactive_daily_limit",
                "proactive_min_interval_minutes",
                "proactive_wake_min_minutes",
                "proactive_wake_max_minutes",
                "diary_enabled",
                "diary_privacy_enabled",
                "diary_peek_enabled",
                "late_night_enabled",
                "late_night_message_enabled",
                "late_night_probability",
                "video_download_enabled",
                "video_download_disclaimer_acknowledged",
                "video_max_size_mb",
                "video_max_duration_seconds",
                "video_total_quota_mb",
            },
            "persona_prompt_opts": {
                "section",
                "use_imported_system_prompt",
                "use_imported_post_history_instructions",
            },
            "immersion": {
                "section",
                "immersion_location_enabled",
                "immersion_closeups_enabled",
                "immersion_smart_home_enabled",
                "immersion_location_radius_m",
            },
            "ui": {
                "section",
                "mode",
            },
            "tts": {
                "section",
                "tts_enabled",
                "tts_provider",
                "tts_voice",
                "tts_model",
                "tts_base_url",
            },
        }[self.section]
        unexpected = self.model_fields_set - allowed
        if unexpected:
            raise ValueError(
                f"settings section {self.section} does not accept: "
                + ", ".join(sorted(unexpected))
            )
        if self.section == "onboarding":
            if not self.model_fields_set.intersection({
                "completed",
                "onboarding_version",
                "onboarding_state",
                "onboarding_last_step",
                "experience_mode",
            }):
                raise ValueError("onboarding settings require at least one state field")
            if self.completed is False and self.onboarding_state == "complete":
                raise ValueError("completed=false conflicts with complete state")
            if self.completed is True and self.onboarding_state == "not_started":
                raise ValueError("completed=true conflicts with not_started state")
            finishing = self.onboarding_state == "complete" or (
                self.completed is True and self.onboarding_state is None
            )
            if finishing:
                if self.onboarding_version not in {None, 2, 3}:
                    raise ValueError("completed onboarding requires version 2 or 3")
                if self.onboarding_last_step not in {None, "finish"}:
                    raise ValueError("completed onboarding requires finish step")
            elif self.completed is True:
                if self.onboarding_version not in {None, 2, 3}:
                    raise ValueError("active onboarding requires version 2 or 3")
            if self.onboarding_state in {"in_progress", "committing"} and self.onboarding_version not in {2, 3}:
                raise ValueError("active onboarding requires version 2 or 3")
        if (
            self.proactive_wake_min_minutes is not None
            and self.proactive_wake_max_minutes is not None
            and self.proactive_wake_min_minutes > self.proactive_wake_max_minutes
        ):
            raise ValueError("proactive wake minimum cannot exceed maximum")
        return self


class UserProfileData(_PayloadModel):
    name: str = Field(default="", max_length=80)
    nickname: str = Field(default="", max_length=80)
    age: int | None = Field(default=None, ge=18, le=120)
    birthday: str = Field(default="", max_length=10)
    identity: str = Field(default="", max_length=500)
    schedule: str = Field(default="", max_length=200)
    interests: list[str] = Field(default_factory=list, max_length=50)
    hobbies: list[str] = Field(default_factory=list, max_length=50)
    favorite_topics: list[str] = Field(default_factory=list, max_length=50)
    favorite_games: list[str] = Field(default_factory=list, max_length=50)
    favorite_anime: list[str] = Field(default_factory=list, max_length=50)
    important_dates: dict[str, str] = Field(default_factory=dict, max_length=50)

    @model_validator(mode="after")
    def validate_bounded_collections(self) -> "UserProfileData":
        for field_name in (
            "interests",
            "hobbies",
            "favorite_topics",
            "favorite_games",
            "favorite_anime",
        ):
            if any(not item.strip() or len(item) > 160 for item in getattr(self, field_name)):
                raise ValueError(f"{field_name} contains an invalid item")
        if any(
            not key.strip()
            or len(key) > 80
            or not value.strip()
            or len(value) > 32
            for key, value in self.important_dates.items()
        ):
            raise ValueError("important_dates contains an invalid entry")
        return self


class UserProfileUpdatePayload(_PayloadModel):
    profile: UserProfileData | None = None
    restore_default: StrictBool | None = None

    @model_validator(mode="after")
    def validate_restore_or_profile(self) -> "UserProfileUpdatePayload":
        if self.restore_default is True:
            return self
        if self.profile is None:
            raise ValueError("user profile update requires a profile")
        return self


COMMAND_PAYLOAD_MODELS: dict[str, type[_PayloadModel]] = {
    "chat:send": ChatSendPayload,
    "chat:cancel": ChatTargetPayload,
    "chat:stop": ChatStopPayload,
    "chat:reveal": ChatTargetPayload,
    "chat:history": ChatHistoryPayload,
    "chat:media": ChatMediaPayload,
    "video:download": VideoDownloadPayload,
    "memory:query": MemoryQueryPayload,
    "memory:list": MemoryListPayload,
    "memory:store": MemoryStorePayload,
    "memory:reinforce": MemoryReinforcePayload,
    "memory:edit": MemoryEditPayload,
    "memory:delete": MemoryTargetPayload,
    "memory:settings:get": EmptyPayload,
    "memory:candidates:list": MemoryCandidateListPayload,
    "memory:candidates:confirm": MemoryCandidateDecisionPayload,
    "memory:candidates:reject": MemoryCandidateDecisionPayload,
    "group:request": EmptyPayload,
    "group:send": GroupSendPayload,
    "sticker:list": StickerListPayload,
    "sticker:collect": StickerCollectPayload,
    "sticker:react": StickerReactPayload,
    "sticker:import": StickerImportPayload,
    "game_state:get": GameStateGetPayload,
    "game_state:put": GameStatePutPayload,
    "game:move": GameMovePayload,
    "immersion:nearby": ImmersionNearbyPayload,
    "immersion:closeup": ImmersionCloseupPayload,
    "immersion:smart_home": ImmersionSmartHomePayload,
    "ambient:get": EmptyPayload,
    "api:budget:get": EmptyPayload,
    "archive:get": EmptyPayload,
    "archive:put": ArchivePutPayload,
    "archive:migrate": ArchivePutPayload,
    "module:list": EmptyPayload,
    "module:control": ModuleControlPayload,
    "diary:request": DiaryRequestPayload,
    "diary:write": EmptyPayload,
    "timeline:request": EmptyPayload,
    "keepsake:list": KeepsakeListPayload,
    "keepsake:add": KeepsakeAddPayload,
    "backup:export": EmptyPayload,
    "backup:import": BackupImportPayload,
    "image:random": ImageRandomPayload,
    "tts:list": EmptyPayload,
    "tts:synthesize": TTSSynthesizePayload,
    "emotion:get": EmptyPayload,
    "persona:get": EmptyPayload,
    "persona:import": PersonaImportPayload,
    "persona:activate": PersonaActivatePayload,
    "relationship:get": EmptyPayload,
    "settings:update": SettingsUpdatePayload,
    "settings:get": EmptyPayload,
    "ai_usage:get": EmptyPayload,
    "ai_usage:grant": AIUsageGrantPayload,
    "ai_usage:revoke": AIUsageRevokePayload,
    "user:profile:get": EmptyPayload,
    "user:profile:update": UserProfileUpdatePayload,
    "anti_ai:status": EmptyPayload,
}

MUTATING_COMMAND_NAMES = frozenset(
    {
        "video:download",
        "memory:candidates:confirm",
        "memory:candidates:reject",
        "memory:store",
        "memory:edit",
        "memory:delete",
        "group:send",
        "sticker:collect",
        "sticker:react",
        "sticker:import",
        "game_state:put",
        "archive:put",
        "archive:migrate",
        "module:control",
        "keepsake:add",
        "persona:import",
        "persona:activate",
        "ai_usage:grant",
        "ai_usage:revoke",
        "backup:import",
        "settings:update",
        "user:profile:update",
    }
)

if frozenset(COMMAND_PAYLOAD_MODELS) != MVP_COMMAND_NAMES:
    raise RuntimeError("every MVP command must have exactly one payload contract")


class PersonaScopeV4(_ContractModel):
    persona_id: str = Field(min_length=1, max_length=128)
    epoch: int = Field(ge=1)
    fingerprint: str = Field(pattern=_FINGERPRINT_PATTERN.pattern)

    @field_validator("persona_id")
    @classmethod
    def validate_persona_id(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("persona_id contains unsupported characters")
        return value


class CommandEnvelopeV4(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    request_id: str = Field(default_factory=lambda: uuid4().hex)
    idempotency_key: str = Field(default_factory=lambda: uuid4().hex)
    command: str = Field(min_length=1, max_length=128)
    persona: PersonaScopeV4
    payload: dict[str, Any] = Field(default_factory=dict)
    causation_id: str | None = Field(default=None, max_length=128)
    created_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, value: int) -> int:
        if value != PROTOCOL_VERSION:
            raise ValueError(f"unsupported protocol version: {value}")
        return value

    @field_validator("request_id", "idempotency_key")
    @classmethod
    def validate_identifier(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("identifier contains unsupported characters")
        return value

    @field_validator("command")
    @classmethod
    def validate_command(cls, value: str) -> str:
        if value not in MVP_COMMAND_NAMES:
            raise ValueError(f"unknown command: {value}")
        return value

    @model_validator(mode="after")
    def validate_payload_contract(self) -> "CommandEnvelopeV4":
        payload_model = COMMAND_PAYLOAD_MODELS[self.command]
        validated = payload_model.model_validate(self.payload)
        if (
            self.command == "chat:send"
            and validated.request_id is not None
            and validated.request_id != self.request_id
        ):
            raise ValueError("chat payload request_id does not match envelope")
        object.__setattr__(
            self,
            "payload",
            validated.model_dump(exclude_none=True),
        )
        return self


class DomainError(_ContractModel):
    code: ErrorCode
    message: str = Field(min_length=1, max_length=500)
    retryable: bool = False
    details: dict[str, Any] = Field(default_factory=dict)


class CommandResultV4(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    request_id: str
    ok: bool
    data: dict[str, Any] | list[Any] | str | int | float | bool | None = None
    error: DomainError | None = None

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, value: int) -> int:
        if value != PROTOCOL_VERSION:
            raise ValueError(f"unsupported protocol version: {value}")
        return value

    @classmethod
    def success(cls, request_id: str, data: Any = None) -> "CommandResultV4":
        return cls(request_id=request_id, ok=True, data=data)

    @classmethod
    def failure(
        cls,
        request_id: str,
        *,
        code: ErrorCode,
        message: str,
        retryable: bool = False,
        details: dict[str, Any] | None = None,
    ) -> "CommandResultV4":
        return cls(
            request_id=request_id,
            ok=False,
            error=DomainError(
                code=code,
                message=message,
                retryable=retryable,
                details=details or {},
            ),
        )

    def model_post_init(self, __context: Any) -> None:
        if self.ok and self.error is not None:
            raise ValueError("successful result cannot carry an error")
        if not self.ok and self.error is None:
            raise ValueError("failed result must carry an error")


class DomainEventV4(_ContractModel):
    protocol_version: int = PROTOCOL_VERSION
    event_id: str = Field(default_factory=lambda: uuid4().hex)
    event_type: str = Field(min_length=1, max_length=128)
    persona: PersonaScopeV4
    payload: dict[str, Any] = Field(default_factory=dict)
    causation_id: str | None = Field(default=None, max_length=128)
    occurred_at_utc: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    payload_version: int = Field(default=1, ge=1)

    @field_validator("event_id", "event_type")
    @classmethod
    def validate_identifier(cls, value: str) -> str:
        if not _ID_PATTERN.fullmatch(value):
            raise ValueError("event identifier contains unsupported characters")
        return value


class V3FrameAdapter:
    """Development-only compatibility boundary; production never downgrades."""

    legacy_protocol_version: ClassVar[int] = 3

    @staticmethod
    def to_v4(frame: dict[str, Any], persona: PersonaScopeV4) -> CommandEnvelopeV4:
        if not isinstance(frame, dict):
            raise TypeError("legacy frame must be an object")
        command = frame.get("type")
        payload = frame.get("payload", {})
        if not isinstance(command, str) or command not in MVP_COMMAND_NAMES:
            raise ValueError("legacy frame has an unknown command")
        if not isinstance(payload, dict):
            raise TypeError("legacy frame payload must be an object")
        request_id = str(frame.get("request_id") or uuid4().hex)
        idempotency_key = str(
            payload.get("idempotency_key")
            or payload.get("client_request_id")
            or request_id
        )
        return CommandEnvelopeV4(
            request_id=request_id,
            idempotency_key=idempotency_key,
            command=command,
            persona=persona,
            payload=payload,
        )

    @staticmethod
    def result_to_v3(
        result: CommandResultV4,
        *,
        response_type: str,
    ) -> dict[str, Any]:
        if result.ok:
            payload = result.data
        else:
            assert result.error is not None
            payload = {
                "ok": False,
                "error": {
                    "code": result.error.code.value,
                    "message": result.error.message,
                    "retryable": result.error.retryable,
                },
            }
        return {
            "type": response_type,
            "request_id": result.request_id,
            "payload": payload,
        }


# Internal source compatibility while the remaining modular-monolith classes
# are renamed independently. All aliases now enforce the V4 wire contract.
PersonaScopeV3 = PersonaScopeV4
CommandEnvelopeV3 = CommandEnvelopeV4
CommandResultV3 = CommandResultV4
DomainEventV3 = DomainEventV4
V2FrameAdapter = V3FrameAdapter


def public_error_message(error: BaseException) -> str:
    """Return a bounded message that cannot impersonate the companion."""

    code = str(getattr(error, "code", "") or "")
    known = {
        "REVERIE_SECURE_STORAGE_UNAVAILABLE": "系统安全凭据存储当前不可用。",
        "REVERIE_VAULT_CORRUPT": "本地凭据保险库无法解密，请先清理或恢复。",
        "REVERIE_VAULT_IO": "本地凭据保险库无法读写。",
    }
    return known.get(code, "请求未完成。技术详情已写入本地日志。")
