[pytest]
minversion = 8.0
addopts = --import-mode=importlib --strict-config --strict-markers
testpaths =
    tests
norecursedirs =
    .git
    .hypothesis
    .pytest_cache
    frontend
    venv
filterwarnings =
    ignore::DeprecationWarning
