/* Generated by script/generate_protocol_contracts.py. Do not edit. */
export const PROTOCOL_VERSION = 4 as const;

export const WSMsgType = {
  CHAT_SEND: "chat:send",
  CHAT_CANCEL: "chat:cancel",
  CHAT_REVEAL: "chat:reveal",
  CHAT_STOP: "chat:stop",
  CHAT_HISTORY: "chat:history",
  CHAT_MEDIA: "chat:media",
  VIDEO_DOWNLOAD: "video:download",
  BRIDGE_AUTH: "bridge:auth",
  LOCAL_MODE_SET: "local_mode:set",
  MEMORY_QUERY: "memory:query",
  MEMORY_LIST: "memory:list",
  MEMORY_EDIT: "memory:edit",
  MEMORY_DELETE: "memory:delete",
  MEMORY_SETTINGS_GET: "memory:settings:get",
  MEMORY_STORE: "memory:store",
  MEMORY_REINFORCE: "memory:reinforce",
  MEMORY_CANDIDATE_LIST: "memory:candidates:list",
  MEMORY_CANDIDATE_CONFIRM: "memory:candidates:confirm",
  MEMORY_CANDIDATE_REJECT: "memory:candidates:reject",
  EMOTION_GET: "emotion:get",
  PERSONA_GET: "persona:get",
  PERSONA_IMPORT: "persona:import",
  PERSONA_ACTIVATE: "persona:activate",
  ARCHIVE_GET: "archive:get",
  ARCHIVE_PUT: "archive:put",
  ARCHIVE_MIGRATE: "archive:migrate",
  MODULE_LIST: "module:list",
  MODULE_CONTROL: "module:control",
  GAME_STATE_GET: "game_state:get",
  GAME_STATE_PUT: "game_state:put",
  GAME_MOVE: "game:move",
  RELATIONSHIP_GET: "relationship:get",
  DIARY_REQUEST: "diary:request",
  DIARY_WRITE: "diary:write",
  TIMELINE_REQUEST: "timeline:request",
  AMBIENT_GET: "ambient:get",
  API_BUDGET_GET: "api:budget:get",
  GROUP_REQUEST: "group:request",
  GROUP_SEND: "group:send",
  IMAGE_RANDOM: "image:random",
  TTS_LIST: "tts:list",
  TTS_SYNTHESIZE: "tts:synthesize",
  SETTINGS_UPDATE: "settings:update",
  SETTINGS_GET: "settings:get",
  AI_USAGE_GET: "ai_usage:get",
  AI_USAGE_GRANT: "ai_usage:grant",
  AI_USAGE_REVOKE: "ai_usage:revoke",
  USER_PROFILE_GET: "user:profile:get",
  USER_PROFILE_UPDATE: "user:profile:update",
  KEEPSAKE_LIST: "keepsake:list",
  KEEPSAKE_ADD: "keepsake:add",
  BACKUP_EXPORT: "backup:export",
  BACKUP_IMPORT: "backup:import",
  STICKER_LIST: "sticker:list",
  STICKER_COLLECT: "sticker:collect",
  STICKER_REACT: "sticker:react",
  STICKER_IMPORT: "sticker:import",
  ANTI_AI_STATUS: "anti_ai:status",
  IMMERSION_NEARBY: "immersion:nearby",
  IMMERSION_CLOSEUP: "immersion:closeup",
  IMMERSION_SMART_HOME: "immersion:smart_home",
  CHAT_CHUNK: "chat:chunk",
  CHAT_BUBBLE: "chat:bubble",
  CHAT_DONE: "chat:done",
  CHAT_TYPING: "chat:typing",
  CHAT_STATE: "chat:state",
  CHAT_ERROR: "chat:error",
  CHAT_RETRACT: "chat:retract",
  CHAT_HISTORY_RESULT: "chat:history:result",
  CHAT_MEDIA_RESULT: "chat:media:result",
  VIDEO_DOWNLOAD_RESULT: "video:download:result",
  VIDEO_DOWNLOAD_PROGRESS: "video:download:progress",
  BRIDGE_AUTH_OK: "bridge:auth_ok",
  BRIDGE_AUTH_ERROR: "bridge:auth_error",
  LOCAL_MODE_STATE: "local_mode:state",
  PROACTIVE_MESSAGE: "proactive:message",
  PROACTIVE_NOTIFY: "proactive:notify",
  EMOTION_UPDATE: "emotion:update",
  MEMORY_RESULT: "memory:result",
  MEMORY_SETTINGS_RESULT: "memory:settings:result",
  MEMORY_CANDIDATE_RESULT: "memory:candidates:result",
  PERSONA_DATA: "persona:data",
  PERSONA_IMPORT_RESULT: "persona:import:result",
  ARCHIVE_RESULT: "archive:result",
  MODULE_RESULT: "module:result",
  GAME_STATE_RESULT: "game_state:result",
  GAME_MOVE_RESULT: "game:move:result",
  RELATIONSHIP_DATA: "relationship:data",
  DIARY_RESULT: "diary:result",
  TIMELINE_RESULT: "timeline:result",
  AMBIENT_RESULT: "ambient:result",
  API_BUDGET_RESULT: "api:budget:result",
  GROUP_RESULT: "group:result",
  IMAGE_RESULT: "image:result",
  TTS_RESULT: "tts:result",
  USER_PROFILE_RESULT: "user:profile:result",
  KEEPSAKE_RESULT: "keepsake:result",
  BACKUP_RESULT: "backup:result",
  SETTINGS_UPDATE_RESULT: "settings:update:result",
  SETTINGS_GET_RESULT: "settings:get:result",
  AI_USAGE_RESULT: "ai_usage:result",
  RUNTIME_ACTIVITY: "runtime:activity",
  STICKER_DATA: "sticker:data",
  ANTI_AI_STATUS_RESULT: "anti_ai:status:result",
  IMMERSION_RESULT: "immersion:result",
  ERROR: "error",
  HEARTBEAT: "heartbeat",
} as const;

export type LegacyMessageType = typeof WSMsgType[keyof typeof WSMsgType];
export type MVPCommandName = "ai_usage:get" | "ai_usage:grant" | "ai_usage:revoke" | "ambient:get" | "anti_ai:status" | "api:budget:get" | "archive:get" | "archive:migrate" | "archive:put" | "backup:export" | "backup:import" | "chat:cancel" | "chat:history" | "chat:media" | "chat:reveal" | "chat:send" | "chat:stop" | "diary:request" | "diary:write" | "emotion:get" | "game:move" | "game_state:get" | "game_state:put" | "group:request" | "group:send" | "image:random" | "immersion:closeup" | "immersion:nearby" | "immersion:smart_home" | "keepsake:add" | "keepsake:list" | "memory:candidates:confirm" | "memory:candidates:list" | "memory:candidates:reject" | "memory:delete" | "memory:edit" | "memory:list" | "memory:query" | "memory:reinforce" | "memory:settings:get" | "memory:store" | "module:control" | "module:list" | "persona:activate" | "persona:get" | "persona:import" | "relationship:get" | "settings:get" | "settings:update" | "sticker:collect" | "sticker:import" | "sticker:list" | "sticker:react" | "timeline:request" | "tts:list" | "tts:synthesize" | "user:profile:get" | "user:profile:update" | "video:download";

export interface PersonaScopeV4 {
  persona_id: string;
  epoch: number;
  fingerprint: string;
}

export interface CommandEnvelopeV4 {
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  idempotency_key: string;
  command: MVPCommandName;
  persona: PersonaScopeV4;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  created_at_utc: string;
}

export interface DomainErrorV4 {
  code: string;
  message: string;
  retryable: boolean;
  details: Record<string, unknown>;
}

export interface CommandResultV4 {
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  ok: boolean;
  data?: unknown;
  error?: DomainErrorV4 | null;
}

export interface DomainEventV4 {
  protocol_version: typeof PROTOCOL_VERSION;
  event_id: string;
  event_type: string;
  persona: PersonaScopeV4;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  occurred_at_utc: string;
  payload_version: number;
}
