/* Generated by script/generate_protocol_contracts.py. Do not edit. */
export const PROTOCOL_VERSION = 3 as const;

export const WSMsgType = {
  CHAT_SEND: "chat:send",
  CHAT_CANCEL: "chat:cancel",
  CHAT_REVEAL: "chat:reveal",
  CHAT_STOP: "chat:stop",
  CHAT_HISTORY: "chat:history",
  BRIDGE_AUTH: "bridge:auth",
  LOCAL_MODE_SET: "local_mode:set",
  MEMORY_QUERY: "memory:query",
  MEMORY_SETTINGS_GET: "memory:settings:get",
  MEMORY_STORE: "memory:store",
  EMOTION_GET: "emotion:get",
  PERSONA_GET: "persona:get",
  PERSONA_IMPORT: "persona:import",
  PERSONA_LIST: "persona:list",
  PERSONA_ACTIVATE: "persona:activate",
  ARCHIVE_GET: "archive:get",
  ARCHIVE_PUT: "archive:put",
  ARCHIVE_MIGRATE: "archive:migrate",
  MODULE_LIST: "module:list",
  MODULE_CONTROL: "module:control",
  GAME_STATE_GET: "game_state:get",
  GAME_STATE_PUT: "game_state:put",
  RELATIONSHIP_GET: "relationship:get",
  DIARY_REQUEST: "diary:request",
  TIMELINE_REQUEST: "timeline:request",
  AMBIENT_GET: "ambient:get",
  API_BUDGET_GET: "api:budget:get",
  GROUP_REQUEST: "group:request",
  GROUP_SEND: "group:send",
  IMAGE_RANDOM: "image:random",
  SETTINGS_UPDATE: "settings:update",
  SETTINGS_GET: "settings:get",
  AI_USAGE_GET: "ai_usage:get",
  AI_USAGE_GRANT: "ai_usage:grant",
  AI_USAGE_REVOKE: "ai_usage:revoke",
  USER_PROFILE_GET: "user:profile:get",
  USER_PROFILE_UPDATE: "user:profile:update",
  KEEPSAKE_LIST: "keepsake:list",
  KEEPSAKE_ADD: "keepsake:add",
  BACKUP_EXPORT: "backup:export",
  BACKUP_IMPORT: "backup:import",
  STICKER_LIST: "sticker:list",
  STICKER_COLLECT: "sticker:collect",
  STICKER_REACT: "sticker:react",
  STICKER_SEND: "sticker:send",
  ANTI_AI_STATUS: "anti_ai:status",
  IMMERSION_NEARBY: "immersion:nearby",
  IMMERSION_CLOSEUP: "immersion:closeup",
  IMMERSION_SMART_HOME: "immersion:smart_home",
  CHAT_CHUNK: "chat:chunk",
  CHAT_BUBBLE: "chat:bubble",
  CHAT_DONE: "chat:done",
  CHAT_TYPING: "chat:typing",
  CHAT_STATE: "chat:state",
  CHAT_ERROR: "chat:error",
  CHAT_RETRACT: "chat:retract",
  CHAT_HISTORY_RESULT: "chat:history:result",
  BRIDGE_AUTH_OK: "bridge:auth_ok",
  BRIDGE_AUTH_ERROR: "bridge:auth_error",
  LOCAL_MODE_STATE: "local_mode:state",
  PROACTIVE_MESSAGE: "proactive:message",
  PROACTIVE_NOTIFY: "proactive:notify",
  EMOTION_UPDATE: "emotion:update",
  MEMORY_RESULT: "memory:result",
  MEMORY_SETTINGS_RESULT: "memory:settings:result",
  PERSONA_DATA: "persona:data",
  PERSONA_IMPORT_RESULT: "persona:import:result",
  ARCHIVE_RESULT: "archive:result",
  MODULE_RESULT: "module:result",
  GAME_STATE_RESULT: "game_state:result",
  RELATIONSHIP_DATA: "relationship:data",
  DIARY_RESULT: "diary:result",
  TIMELINE_RESULT: "timeline:result",
  AMBIENT_RESULT: "ambient:result",
  API_BUDGET_RESULT: "api:budget:result",
  GROUP_RESULT: "group:result",
  IMAGE_RESULT: "image:result",
  USER_PROFILE_RESULT: "user:profile:result",
  KEEPSAKE_RESULT: "keepsake:result",
  BACKUP_RESULT: "backup:result",
  SETTINGS_UPDATE_RESULT: "settings:update:result",
  SETTINGS_GET_RESULT: "settings:get:result",
  AI_USAGE_RESULT: "ai_usage:result",
  RUNTIME_ACTIVITY: "runtime:activity",
  STICKER_DATA: "sticker:data",
  ANTI_AI_STATUS_RESULT: "anti_ai:status:result",
  IMMERSION_RESULT: "immersion:result",
  ERROR: "error",
  HEARTBEAT: "heartbeat",
} as const;

export type LegacyMessageType = typeof WSMsgType[keyof typeof WSMsgType];

export interface PersonaScopeV3 {
  persona_id: string;
  epoch: number;
  fingerprint: string;
}

export interface CommandEnvelopeV3 {
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  idempotency_key: string;
  command: LegacyMessageType;
  persona: PersonaScopeV3;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  created_at_utc: string;
}

export interface DomainErrorV3 {
  code: string;
  message: string;
  retryable: boolean;
  details: Record<string, unknown>;
}

export interface CommandResultV3 {
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  ok: boolean;
  data?: unknown;
  error?: DomainErrorV3 | null;
}

export interface DomainEventV3 {
  protocol_version: typeof PROTOCOL_VERSION;
  event_id: string;
  event_type: string;
  persona: PersonaScopeV3;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  occurred_at_utc: string;
  payload_version: number;
}
