"""Generate renderer contracts from src.kernel.contracts."""

from __future__ import annotations

import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.kernel.contracts import (  # noqa: E402
    COMMAND_PAYLOAD_MODELS,
    COMMAND_NAMES,
    CommandEnvelopeV4,
    CommandResultV4,
    DomainEventV4,
    LEGACY_MESSAGE_TYPES,
    MVP_EVENT_NAMES,
)


TS_TARGET = ROOT / "frontend" / "src" / "contracts" / "protocolV4.generated.ts"
ELECTRON_TARGET = ROOT / "frontend" / "electron" / "protocol-v4.generated.cjs"
PRELOAD_TARGET = ROOT / "frontend" / "electron" / "preload.js"
SCHEMA_TARGET = ROOT / "config" / "protocol-v4.schema.json"
PRELOAD_BEGIN = "/* BEGIN GENERATED PROTOCOL V4 COMMANDS */"
PRELOAD_END = "/* END GENERATED PROTOCOL V4 COMMANDS */"


def typescript() -> str:
    constants = "\n".join(
        f"  {name}: {json.dumps(value)}," for name, value in LEGACY_MESSAGE_TYPES
    )
    commands = " | ".join(json.dumps(value) for value in sorted(COMMAND_NAMES))
    return f"""/* Generated by script/generate_protocol_contracts.py. Do not edit. */
export const PROTOCOL_VERSION = 4 as const;

export const WSMsgType = {{
{constants}
}} as const;

export type LegacyMessageType = typeof WSMsgType[keyof typeof WSMsgType];
export type MVPCommandName = {commands};

export interface PersonaScopeV4 {{
  persona_id: string;
  epoch: number;
  fingerprint: string;
}}

export interface CommandEnvelopeV4 {{
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  idempotency_key: string;
  command: MVPCommandName;
  persona: PersonaScopeV4;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  created_at_utc: string;
}}

export interface DomainErrorV4 {{
  code: string;
  message: string;
  retryable: boolean;
  details: Record<string, unknown>;
}}

export interface CommandResultV4 {{
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  ok: boolean;
  data?: unknown;
  error?: DomainErrorV4 | null;
}}

export interface DomainEventV4 {{
  protocol_version: typeof PROTOCOL_VERSION;
  event_id: string;
  event_type: string;
  persona: PersonaScopeV4;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  occurred_at_utc: string;
  payload_version: number;
}}
"""


def electron_contracts() -> str:
    commands = ",\n".join(
        f"  {json.dumps(value)}" for value in sorted(COMMAND_NAMES)
    )
    messages = ",\n".join(
        f"  {json.dumps(value)}" for value in sorted(MVP_EVENT_NAMES)
    )
    return f"""/* Generated by script/generate_protocol_contracts.py. Do not edit. */
'use strict';

const COMMAND_NAMES = Object.freeze(new Set([
{commands}
]));
const MESSAGE_NAMES = Object.freeze(new Set([
{messages}
]));

module.exports = {{ COMMAND_NAMES, MESSAGE_NAMES }};
"""


def preload_command_allowlist() -> str:
    commands = ",\n".join(
        f"  {json.dumps(value)}" for value in sorted(COMMAND_NAMES)
    )
    return f"""{PRELOAD_BEGIN}
const COMMAND_NAMES = Object.freeze(new Set([
{commands}
]));
{PRELOAD_END}"""


def update_preload() -> None:
    source = PRELOAD_TARGET.read_text(encoding="utf-8")
    before, separator, remainder = source.partition(PRELOAD_BEGIN)
    if not separator:
        raise RuntimeError(f"missing generated preload marker: {PRELOAD_BEGIN}")
    _current, separator, after = remainder.partition(PRELOAD_END)
    if not separator:
        raise RuntimeError(f"missing generated preload marker: {PRELOAD_END}")
    PRELOAD_TARGET.write_text(
        before + preload_command_allowlist() + after,
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    TS_TARGET.parent.mkdir(parents=True, exist_ok=True)
    TS_TARGET.write_text(typescript(), encoding="utf-8", newline="\n")
    ELECTRON_TARGET.write_text(electron_contracts(), encoding="utf-8", newline="\n")
    update_preload()
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://reverie.local/schemas/protocol-v4.json",
        "title": "Reverie Protocol V4",
        "$defs": {
            "CommandEnvelopeV4": CommandEnvelopeV4.model_json_schema(),
            "CommandResultV4": CommandResultV4.model_json_schema(),
            "DomainEventV4": DomainEventV4.model_json_schema(),
            "CommandPayloadsV4": {
                command: model.model_json_schema()
                for command, model in sorted(COMMAND_PAYLOAD_MODELS.items())
            },
        },
    }
    SCHEMA_TARGET.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
