"""Generate renderer contracts from src.kernel.contracts."""

from __future__ import annotations

import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.kernel.contracts import (  # noqa: E402
    COMMAND_NAMES,
    CommandEnvelopeV3,
    CommandResultV3,
    DomainEventV3,
    LEGACY_MESSAGE_TYPES,
)


TS_TARGET = ROOT / "frontend" / "src" / "contracts" / "protocolV3.generated.ts"
ELECTRON_TARGET = ROOT / "frontend" / "electron" / "protocol-v3.generated.cjs"
SCHEMA_TARGET = ROOT / "config" / "protocol-v3.schema.json"


def typescript() -> str:
    constants = "\n".join(
        f"  {name}: {json.dumps(value)}," for name, value in LEGACY_MESSAGE_TYPES
    )
    return f"""/* Generated by script/generate_protocol_contracts.py. Do not edit. */
export const PROTOCOL_VERSION = 3 as const;

export const WSMsgType = {{
{constants}
}} as const;

export type LegacyMessageType = typeof WSMsgType[keyof typeof WSMsgType];

export interface PersonaScopeV3 {{
  persona_id: string;
  epoch: number;
  fingerprint: string;
}}

export interface CommandEnvelopeV3 {{
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  idempotency_key: string;
  command: LegacyMessageType;
  persona: PersonaScopeV3;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  created_at_utc: string;
}}

export interface DomainErrorV3 {{
  code: string;
  message: string;
  retryable: boolean;
  details: Record<string, unknown>;
}}

export interface CommandResultV3 {{
  protocol_version: typeof PROTOCOL_VERSION;
  request_id: string;
  ok: boolean;
  data?: unknown;
  error?: DomainErrorV3 | null;
}}

export interface DomainEventV3 {{
  protocol_version: typeof PROTOCOL_VERSION;
  event_id: string;
  event_type: string;
  persona: PersonaScopeV3;
  payload: Record<string, unknown>;
  causation_id?: string | null;
  occurred_at_utc: string;
  payload_version: number;
}}
"""


def electron_contracts() -> str:
    commands = ",\n".join(
        f"  {json.dumps(value)}" for value in sorted(COMMAND_NAMES)
    )
    messages = ",\n".join(
        f"  {json.dumps(value)}" for _name, value in LEGACY_MESSAGE_TYPES
    )
    return f"""/* Generated by script/generate_protocol_contracts.py. Do not edit. */
'use strict';

const COMMAND_NAMES = Object.freeze(new Set([
{commands}
]));
const MESSAGE_NAMES = Object.freeze(new Set([
{messages}
]));

module.exports = {{ COMMAND_NAMES, MESSAGE_NAMES }};
"""


def main() -> None:
    TS_TARGET.parent.mkdir(parents=True, exist_ok=True)
    TS_TARGET.write_text(typescript(), encoding="utf-8", newline="\n")
    ELECTRON_TARGET.write_text(electron_contracts(), encoding="utf-8", newline="\n")
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://reverie.local/schemas/protocol-v3.json",
        "title": "Reverie Protocol V3",
        "$defs": {
            "CommandEnvelopeV3": CommandEnvelopeV3.model_json_schema(),
            "CommandResultV3": CommandResultV3.model_json_schema(),
            "DomainEventV3": DomainEventV3.model_json_schema(),
        },
    }
    SCHEMA_TARGET.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
